[{"url": "https://api.github.com/repos/hgrecco/pint/issues/1646", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1646/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1646/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1646/events", "html_url": "https://github.com/hgrecco/pint/issues/1646", "id": 1444216361, "node_id": "I_kwDOAEygxM5WFP4p", "number": 1646, "title": "pint-convert does not work anymore after freezing UnitDefinition", "user": {"login": "jules-ch", "id": 43635101, "node_id": "MDQ6VXNlcjQzNjM1MTAx", "avatar_url": "https://avatars.githubusercontent.com/u/43635101?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jules-ch", "html_url": "https://github.com/jules-ch", "followers_url": "https://api.github.com/users/jules-ch/followers", "following_url": "https://api.github.com/users/jules-ch/following{/other_user}", "gists_url": "https://api.github.com/users/jules-ch/gists{/gist_id}", "starred_url": "https://api.github.com/users/jules-ch/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jules-ch/subscriptions", "organizations_url": "https://api.github.com/users/jules-ch/orgs", "repos_url": "https://api.github.com/users/jules-ch/repos", "events_url": "https://api.github.com/users/jules-ch/events{/privacy}", "received_events_url": "https://api.github.com/users/jules-ch/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2022-11-10T16:35:06Z", "updated_at": "2023-04-27T05:41:48Z", "closed_at": "2023-04-27T05:41:48Z", "author_association": "COLLABORATOR", "active_lock_reason": null, "body": "Since last releases, UnitDefinition has been frozen but pint-convert script was mutating it to inject correlation uncertainties between constant.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1646/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1646/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1523", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1523/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1523/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1523/events", "html_url": "https://github.com/hgrecco/pint/issues/1523", "id": 1240123449, "node_id": "I_kwDOAEygxM5J6sg5", "number": 1523, "title": "Locale-based formatting TypeError", "user": {"login": "GillesJ", "id": 9109832, "node_id": "MDQ6VXNlcjkxMDk4MzI=", "avatar_url": "https://avatars.githubusercontent.com/u/9109832?v=4", "gravatar_id": "", "url": "https://api.github.com/users/GillesJ", "html_url": "https://github.com/GillesJ", "followers_url": "https://api.github.com/users/GillesJ/followers", "following_url": "https://api.github.com/users/GillesJ/following{/other_user}", "gists_url": "https://api.github.com/users/GillesJ/gists{/gist_id}", "starred_url": "https://api.github.com/users/GillesJ/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/GillesJ/subscriptions", "organizations_url": "https://api.github.com/users/GillesJ/orgs", "repos_url": "https://api.github.com/users/GillesJ/repos", "events_url": "https://api.github.com/users/GillesJ/events{/privacy}", "received_events_url": "https://api.github.com/users/GillesJ/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2022-05-18T15:16:10Z", "updated_at": "2022-11-22T20:35:46Z", "closed_at": "2022-11-22T20:35:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "For localization of units I am testing pint + babel as per [tutorial example](https://pint.readthedocs.io/en/stable/tutorial.html#localizing). I suspect the babel-provided CLDR data is not properly parsed or passed to the pint formatter based off the stack-trace.\r\n\r\nExample:\r\n```\r\nureg = pint.UnitRegistry()\r\naccel = 1.3 * ureg['meter/second**2']\r\nprint(str(accel.format_babel(locale='fr_FR')))\r\n\r\nureg = pint.UnitRegistry(fmt_locale='fr_FR')\r\naccel = 1.3 * ureg['meter/second**2']\r\nprint(str(accel))\r\n```\r\nExpected output:\r\n```\r\n>> '1.3 m\u00e8tre par seconde\u00b2'\r\n>> '1.3 m\u00e8tre par seconde\u00b2'\r\n```\r\nStacktrace / error:\r\n```\r\nTraceback (most recent call last):\r\n  File \"/Users/gilles/repos/testpint/test.py\", line 5, in <module>\r\n    str(accel.format_babel(locale='fr_FR'))\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/quantity.py\", line 483, in format_babel\r\n    obj.units.format_babel(spec, **kwspec),\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/unit.py\", line 124, in format_babel\r\n    return units.format_babel(spec, registry=self._REGISTRY, **kwspec)\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/util.py\", line 466, in format_babel\r\n    return format_unit(self, spec, registry=registry, **kwspec)\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py\", line 411, in format_unit\r\n    return fmt(unit, registry=registry, **options)\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py\", line 227, in format_default\r\n    return formatter(\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py\", line 366, in formatter\r\n    neg_ret = _join(division_fmt, neg_terms)\r\n  File \"/Users/gilles/.local/share/virtualenvs/testpint-hlpj48ZU/lib/python3.9/site-packages/pint/formatting.py\", line 42, in _join\r\n    if not __JOIN_REG_EXP.search(fmt):\r\nTypeError: expected string or bytes-like object\r\n```\r\n\r\nPython version: 3.9\r\npint==0.19.2\r\nbabel==2.10.1\r\n\r\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1523/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1523/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1505", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1505/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1505/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1505/events", "html_url": "https://github.com/hgrecco/pint/issues/1505", "id": 1197658837, "node_id": "I_kwDOAEygxM5HYtLV", "number": 1505, "title": "Decimal registry parses unit expression without scaling factor using float instead of decimal", "user": {"login": "Flix6x", "id": 30658763, "node_id": "MDQ6VXNlcjMwNjU4NzYz", "avatar_url": "https://avatars.githubusercontent.com/u/30658763?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Flix6x", "html_url": "https://github.com/Flix6x", "followers_url": "https://api.github.com/users/Flix6x/followers", "following_url": "https://api.github.com/users/Flix6x/following{/other_user}", "gists_url": "https://api.github.com/users/Flix6x/gists{/gist_id}", "starred_url": "https://api.github.com/users/Flix6x/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Flix6x/subscriptions", "organizations_url": "https://api.github.com/users/Flix6x/orgs", "repos_url": "https://api.github.com/users/Flix6x/repos", "events_url": "https://api.github.com/users/Flix6x/events{/privacy}", "received_events_url": "https://api.github.com/users/Flix6x/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 10, "created_at": "2022-04-08T18:22:50Z", "updated_at": "2023-04-28T22:29:45Z", "closed_at": "2023-04-28T22:29:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "I found the following unexpected difference between float type and decimal type registries:\r\n\r\n```\r\nimport decimal\r\nimport pint\r\n\r\nur = pint.UnitRegistry(non_int_type=decimal.Decimal)\r\n\r\npint.Quantity(\"m/s\").to(\"km/h\")  # <Quantity(3.6, 'kilometer / hour')>\r\nur.Quantity(\"m/s\").to(\"km/h\")  # fails with TypeError: unsupported operand type(s) for *: 'float' and 'decimal.Decimal'\r\n```\r\nIf I add an explicit scaling factor, it works as expected:\r\n```\r\npint.Quantity(\"1m/s\").to(\"km/h\")  # <Quantity(3.6, 'kilometer / hour')>\r\nur.Quantity(\"1m/s\").to(\"km/h\")  # <Quantity(3.60000, 'kilometer / hour')>\r\n```\r\n\r\nI think that underlying this there's a problem with the parsing of the input string, but I could use some help figuring out where the float is being introduced.\r\n\r\nHere's what a relevant test could look like:\r\n```\r\ndef test_decimal_magnitude():\r\n    ur = pint.UnitRegistry(non_int_type=decimal.Decimal)\r\n\r\n    assert isinstance(ur.Quantity(\"1m/s\").magnitude, decimal.Decimal)\r\n    assert not isinstance(ur.Quantity(\"m/s\").magnitude, float)  # unexpected success (magnitude should not be a float)\r\n    assert isinstance(ur.Quantity(\"m/s\").magnitude, decimal.Decimal)  # unexpected fail (magnitude should be a decimal)\r\n```\r\n\r\nBoth `pint==0.18` and `pint==0.19.1` have this problem.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1505/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1505/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1427", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1427/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1427/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1427/events", "html_url": "https://github.com/hgrecco/pint/issues/1427", "id": 1066246599, "node_id": "I_kwDOAEygxM4_jaHH", "number": 1427, "title": "to_reduced_units() fails with g*t/kg", "user": {"login": "brwe", "id": 4320215, "node_id": "MDQ6VXNlcjQzMjAyMTU=", "avatar_url": "https://avatars.githubusercontent.com/u/4320215?v=4", "gravatar_id": "", "url": "https://api.github.com/users/brwe", "html_url": "https://github.com/brwe", "followers_url": "https://api.github.com/users/brwe/followers", "following_url": "https://api.github.com/users/brwe/following{/other_user}", "gists_url": "https://api.github.com/users/brwe/gists{/gist_id}", "starred_url": "https://api.github.com/users/brwe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/brwe/subscriptions", "organizations_url": "https://api.github.com/users/brwe/orgs", "repos_url": "https://api.github.com/users/brwe/repos", "events_url": "https://api.github.com/users/brwe/events{/privacy}", "received_events_url": "https://api.github.com/users/brwe/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2021-11-29T16:32:09Z", "updated_at": "2022-01-31T13:17:15Z", "closed_at": "2022-01-31T13:17:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "In am trying to run the following example:\r\n```\r\nimport pint\r\n\r\nureg = pint.UnitRegistry()\r\n \r\nridiculous_factor = 0.5 * ureg.g * ureg.t / ureg.kg\r\nridiculous_factor.to_reduced_units()\r\n```\r\nBut this fails with:\r\n```\r\n---------------------------------------------------------------------------\r\nDimensionalityError                       Traceback (most recent call last)\r\n<ipython-input-211-e3a1dda5eff7> in <module>\r\n      4 \r\n      5 ridiculous_factor = 0.5 * ureg.g * ureg.t / ureg.kg\r\n----> 6 ridiculous_factor.to_reduced_units()\r\n\r\n~/.local/lib/python3.9/site-packages/pint/quantity.py in to_reduced_units(self)\r\n    800         # can we make this more efficient?\r\n    801         newq = copy.copy(self)\r\n--> 802         newq.ito_reduced_units()\r\n    803         return newq\r\n    804 \r\n\r\n~/.local/lib/python3.9/site-packages/pint/quantity.py in ito_reduced_units(self)\r\n    790                         break\r\n    791 \r\n--> 792         return self.ito(newunits)\r\n    793 \r\n    794     def to_reduced_units(self) -> Quantity[_MagnitudeType]:\r\n\r\n~/.local/lib/python3.9/site-packages/pint/quantity.py in ito(self, other, *contexts, **ctx_kwargs)\r\n    699         other = to_units_container(other, self._REGISTRY)\r\n    700 \r\n--> 701         self._magnitude = self._convert_magnitude(other, *contexts, **ctx_kwargs)\r\n    702         self._units = other\r\n    703 \r\n\r\n~/.local/lib/python3.9/site-packages/pint/quantity.py in _convert_magnitude(self, other, *contexts, **ctx_kwargs)\r\n    678                 return self._REGISTRY.convert(self._magnitude, self._units, other)\r\n    679 \r\n--> 680         return self._REGISTRY.convert(\r\n    681             self._magnitude,\r\n    682             self._units,\r\n\r\n~/.local/lib/python3.9/site-packages/pint/registry.py in convert(self, value, src, dst, inplace)\r\n   1001             return value\r\n   1002 \r\n-> 1003         return self._convert(value, src, dst, inplace)\r\n   1004 \r\n   1005     def _convert(self, value, src, dst, inplace=False, check_dimensionality=True):\r\n\r\n~/.local/lib/python3.9/site-packages/pint/registry.py in _convert(self, value, src, dst, inplace)\r\n   1915                 value, src = src._magnitude, src._units\r\n   1916 \r\n-> 1917         return super()._convert(value, src, dst, inplace)\r\n   1918 \r\n   1919     def _get_compatible_units(self, input_units, group_or_system):\r\n\r\n~/.local/lib/python3.9/site-packages/pint/registry.py in _convert(self, value, src, dst, inplace)\r\n   1516 \r\n   1517         if not (src_offset_unit or dst_offset_unit):\r\n-> 1518             return super()._convert(value, src, dst, inplace)\r\n   1519 \r\n   1520         src_dim = self._get_dimensionality(src)\r\n\r\n~/.local/lib/python3.9/site-packages/pint/registry.py in _convert(self, value, src, dst, inplace, check_dimensionality)\r\n   1034             # then the conversion cannot be performed.\r\n   1035             if src_dim != dst_dim:\r\n-> 1036                 raise DimensionalityError(src, dst, src_dim, dst_dim)\r\n   1037 \r\n   1038         # Here src and dst have only multiplicative units left. Thus we can\r\n\r\nDimensionalityError: Cannot convert from 'gram * metric_ton / kilogram' ([mass]) to 'dimensionless' (dimensionless)\r\n```\r\nIf I replace the `g` with `kg` all works as expected.  \r\nVersion is v0.18\r\n\r\nAny pointer appreciated.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1427/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1427/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1381", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1381/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1381/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1381/events", "html_url": "https://github.com/hgrecco/pint/issues/1381", "id": 986509894, "node_id": "MDU6SXNzdWU5ODY1MDk4OTQ=", "number": 1381, "title": "Wrong calculation when using temperature prefixes ", "user": {"login": "Christian-Mueller", "id": 23061139, "node_id": "MDQ6VXNlcjIzMDYxMTM5", "avatar_url": "https://avatars.githubusercontent.com/u/23061139?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Christian-Mueller", "html_url": "https://github.com/Christian-Mueller", "followers_url": "https://api.github.com/users/Christian-Mueller/followers", "following_url": "https://api.github.com/users/Christian-Mueller/following{/other_user}", "gists_url": "https://api.github.com/users/Christian-Mueller/gists{/gist_id}", "starred_url": "https://api.github.com/users/Christian-Mueller/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Christian-Mueller/subscriptions", "organizations_url": "https://api.github.com/users/Christian-Mueller/orgs", "repos_url": "https://api.github.com/users/Christian-Mueller/repos", "events_url": "https://api.github.com/users/Christian-Mueller/events{/privacy}", "received_events_url": "https://api.github.com/users/Christian-Mueller/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2021-09-02T10:22:56Z", "updated_at": "2023-04-27T03:03:47Z", "closed_at": "2023-04-27T03:03:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm doing following conversion:\r\n\r\n```\r\nfrom pint import UnitRegistry\r\n\r\nureg = UnitRegistry()\r\nt = ureg.Quantity(20, ureg.degC)\r\nprint(t.to(ureg.millidegC))\r\n```\r\n\r\noutput:\r\n`293150.0 millidegree_Celsius`\r\n\r\nIt seems like prefixes for degree Celsius are not handled correctly. The result should be 20000 millidegree_Celsius.\r\nLooks like it changes the unit to Kelvin internally.\r\nIt this a known issue? Is there a workaround for my use case?\r\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1381/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1381/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1304", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1304/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1304/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1304/events", "html_url": "https://github.com/hgrecco/pint/issues/1304", "id": 887661434, "node_id": "MDU6SXNzdWU4ODc2NjE0MzQ=", "number": 1304, "title": "\"Redefining\" warning raised when @alias being added", "user": {"login": "stringfellow", "id": 62915, "node_id": "MDQ6VXNlcjYyOTE1", "avatar_url": "https://avatars.githubusercontent.com/u/62915?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stringfellow", "html_url": "https://github.com/stringfellow", "followers_url": "https://api.github.com/users/stringfellow/followers", "following_url": "https://api.github.com/users/stringfellow/following{/other_user}", "gists_url": "https://api.github.com/users/stringfellow/gists{/gist_id}", "starred_url": "https://api.github.com/users/stringfellow/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stringfellow/subscriptions", "organizations_url": "https://api.github.com/users/stringfellow/orgs", "repos_url": "https://api.github.com/users/stringfellow/repos", "events_url": "https://api.github.com/users/stringfellow/events{/privacy}", "received_events_url": "https://api.github.com/users/stringfellow/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2021-05-11T15:36:25Z", "updated_at": "2022-05-29T14:50:54Z", "closed_at": "2022-05-29T14:50:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "When trying to add `@alias` definitions for particular units (see `degree_Celsius` example below), the registry warns of redefinition when it is just adding a new alias. This doesn't happen for all units, but not sure why (see `volt` example below).\r\n\r\n\r\n## `degree_Celsius` example\r\n```pycon\r\nIn [1]: import logging; logging.basicConfig(level=logging.DEBUG)\r\n\r\nIn [2]: from pint import UnitRegistry; ureg = UnitRegistry()\r\n\r\nIn [3]: ureg.parse_expression('degC')\r\nOut[3]: 1 <Unit('degree_Celsius')>\r\n\r\nIn [4]: ureg.define('@alias degree_Celsius = Deg_C')\r\nWARNING:pint.util:Redefining 'degree_Celsius' (<class 'pint.definitions.UnitDefinition'>)\r\nWARNING:pint.util:Redefining '\u00b0C' (<class 'pint.definitions.UnitDefinition'>)\r\nWARNING:pint.util:Redefining 'celsius' (<class 'pint.definitions.UnitDefinition'>)\r\nWARNING:pint.util:Redefining 'degC' (<class 'pint.definitions.UnitDefinition'>)\r\nWARNING:pint.util:Redefining 'degreeC' (<class 'pint.definitions.UnitDefinition'>)\r\nWARNING:pint.util:Redefining 'Deg_C' (<class 'pint.definitions.UnitDefinition'>)\r\n\r\nIn [5]: ureg.parse_expression('Deg_C')\r\nOut[5]: 1 <Unit('degree_Celsius')>\r\n```\r\n\r\n## `volt` example\r\n```pycon\r\nIn [1]: import logging; logging.basicConfig(level=logging.DEBUG)\r\n\r\nIn [2]: from pint import UnitRegistry; ureg = UnitRegistry()\r\n\r\n...\r\n\r\nIn [20]: ureg.parse_expression('volt')\r\nOut[20]: 1 <Unit('volt')>\r\n\r\nIn [21]: ureg.define('@alias volt = Volt = vlt = Vlt = v')\r\n\r\nIn [22]: ureg.parse_expression('Vlt')\r\nOut[22]: 1 <Unit('volt')>\r\n```", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1304/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1304/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1184", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1184/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1184/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1184/events", "html_url": "https://github.com/hgrecco/pint/issues/1184", "id": 717174380, "node_id": "MDU6SXNzdWU3MTcxNzQzODA=", "number": 1184, "title": "how to avoid float/int casting error with to_reduced_units() on integer arrays", "user": {"login": "CagtayFabry", "id": 43667554, "node_id": "MDQ6VXNlcjQzNjY3NTU0", "avatar_url": "https://avatars.githubusercontent.com/u/43667554?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CagtayFabry", "html_url": "https://github.com/CagtayFabry", "followers_url": "https://api.github.com/users/CagtayFabry/followers", "following_url": "https://api.github.com/users/CagtayFabry/following{/other_user}", "gists_url": "https://api.github.com/users/CagtayFabry/gists{/gist_id}", "starred_url": "https://api.github.com/users/CagtayFabry/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CagtayFabry/subscriptions", "organizations_url": "https://api.github.com/users/CagtayFabry/orgs", "repos_url": "https://api.github.com/users/CagtayFabry/repos", "events_url": "https://api.github.com/users/CagtayFabry/events{/privacy}", "received_events_url": "https://api.github.com/users/CagtayFabry/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-10-08T09:23:47Z", "updated_at": "2022-01-15T16:23:00Z", "closed_at": "2022-01-15T16:23:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "What is the best approach to avoid casting errors when working with integer arrays? Is there any way to enforce casting to `float` for unit conversions?\r\n\r\nThe following example works with `to_base_units()` on all inputs but fails with `to_reduced_units()` once any kind of array gets introduced:\r\n~~~python\r\nimport pint\r\nureg = pint.UnitRegistry()\r\nQ_ = ureg.Quantity\r\n\r\nQ_(3, \"s * ms\").to_base_units() # works\r\nQ_([3,4], \"s * ms\").to_base_units() # works, results are float\r\n\r\nQ_(3, \"s * ms\").to_reduced_units() # works\r\nQ_([3,4], \"s * ms\").to_reduced_units() # fails\r\n\r\nUFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'\r\n~~~\r\n`to_reduced_units()` seems call `ito_reduced_units()` almost immediately which produces the error.\r\n\r\nWith `force_ndarray_like=True` it obviously stops working for scalar inputs as well.\r\n~~~python\r\nimport pint\r\nureg = pint.UnitRegistry(force_ndarray_like=True)\r\nQ_ = ureg.Quantity\r\n\r\nQ_(3, \"s * ms\").to_reduced_units()\r\n\r\nUFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'\r\n~~~\r\n\r\nIf possible I would like to catch this behavior as early as possible because it can be quite confusing for new users who might not consider explicitly casting their inputs as `float` and encounter this error at some later point during their analysis.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1184/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1184/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1144", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1144/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1144/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1144/events", "html_url": "https://github.com/hgrecco/pint/issues/1144", "id": 678195824, "node_id": "MDU6SXNzdWU2NzgxOTU4MjQ=", "number": 1144, "title": "Original object modified when subtracting degree_Farenheit from delta_degree_Celsius", "user": {"login": "knightofni-i", "id": 69620390, "node_id": "MDQ6VXNlcjY5NjIwMzkw", "avatar_url": "https://avatars.githubusercontent.com/u/69620390?v=4", "gravatar_id": "", "url": "https://api.github.com/users/knightofni-i", "html_url": "https://github.com/knightofni-i", "followers_url": "https://api.github.com/users/knightofni-i/followers", "following_url": "https://api.github.com/users/knightofni-i/following{/other_user}", "gists_url": "https://api.github.com/users/knightofni-i/gists{/gist_id}", "starred_url": "https://api.github.com/users/knightofni-i/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/knightofni-i/subscriptions", "organizations_url": "https://api.github.com/users/knightofni-i/orgs", "repos_url": "https://api.github.com/users/knightofni-i/repos", "events_url": "https://api.github.com/users/knightofni-i/events{/privacy}", "received_events_url": "https://api.github.com/users/knightofni-i/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-13T06:45:09Z", "updated_at": "2020-08-29T01:24:11Z", "closed_at": "2020-08-29T01:24:11Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Example code to repeat the issue:\r\n`from pint import Quantity`\r\n`test1 = Quantity([-287.78,  -32.24,   -1.94,   -1.94], 'delta_degree_Celsius')`\r\n`test2 = Quantity(70.0, 'degree_Fahrenheit')`\r\n`test1-test2`\r\n\r\nThis results in the value of test1 being unintentionally modified to `Quantity([-518.004,  -58.032,   -3.492,   -3.492], 'delta_degree_Celsius')`. The incorrect line in the source is linked here:\r\nhttps://github.com/hgrecco/pint/blob/3d99581a808f8c0b5445bb43820a2b82815425d1/pint/quantity.py#L1030\r\nThe linked line should be corrected to read:\r\n`magnitude = op(self.to(tu).magnitude, other._magnitude)`\r\n\r\n(First bug report so let me know if something should be adjusted)", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1144/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1144/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1142", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1142/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1142/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1142/events", "html_url": "https://github.com/hgrecco/pint/issues/1142", "id": 676291945, "node_id": "MDU6SXNzdWU2NzYyOTE5NDU=", "number": 1142, "title": "Quantity __new__ not parsing units string properly if some metric terms are abbreviated and some are not", "user": {"login": "klindsay28", "id": 15570875, "node_id": "MDQ6VXNlcjE1NTcwODc1", "avatar_url": "https://avatars.githubusercontent.com/u/15570875?v=4", "gravatar_id": "", "url": "https://api.github.com/users/klindsay28", "html_url": "https://github.com/klindsay28", "followers_url": "https://api.github.com/users/klindsay28/followers", "following_url": "https://api.github.com/users/klindsay28/following{/other_user}", "gists_url": "https://api.github.com/users/klindsay28/gists{/gist_id}", "starred_url": "https://api.github.com/users/klindsay28/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/klindsay28/subscriptions", "organizations_url": "https://api.github.com/users/klindsay28/orgs", "repos_url": "https://api.github.com/users/klindsay28/repos", "events_url": "https://api.github.com/users/klindsay28/events{/privacy}", "received_events_url": "https://api.github.com/users/klindsay28/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-08-10T17:18:20Z", "updated_at": "2022-03-28T11:34:59Z", "closed_at": "2022-03-28T11:34:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I run the code\r\n```\r\nfrom pint import UnitRegistry\r\nureg = UnitRegistry()\r\nunit_str = \"cm centimeter cm centimeter\"\r\nprint(ureg.Quantity(1.0, units=ureg(unit_str)))\r\nprint(ureg.Quantity(1.0, units=unit_str))\r\n```\r\nI get the output\r\n```\r\n1.0 centimeter ** 4\r\n1.0 centimeter ** 2\r\n```\r\n\r\nI expect the output\r\n```\r\n1.0 centimeter ** 4\r\n1.0 centimeter ** 4\r\n```\r\n\r\nIt seems like if `units` is a string, then `cm` in `units` is getting ignored if `centimeter` is present.\r\n\r\nThis is with `pint 0.14`.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1142/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1142/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/1017", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/1017/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/1017/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/1017/events", "html_url": "https://github.com/hgrecco/pint/issues/1017", "id": 561176463, "node_id": "MDU6SXNzdWU1NjExNzY0NjM=", "number": 1017, "title": "Pickled Quantity Changes Type", "user": {"login": "SimonBoothroyd", "id": 22272126, "node_id": "MDQ6VXNlcjIyMjcyMTI2", "avatar_url": "https://avatars.githubusercontent.com/u/22272126?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SimonBoothroyd", "html_url": "https://github.com/SimonBoothroyd", "followers_url": "https://api.github.com/users/SimonBoothroyd/followers", "following_url": "https://api.github.com/users/SimonBoothroyd/following{/other_user}", "gists_url": "https://api.github.com/users/SimonBoothroyd/gists{/gist_id}", "starred_url": "https://api.github.com/users/SimonBoothroyd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SimonBoothroyd/subscriptions", "organizations_url": "https://api.github.com/users/SimonBoothroyd/orgs", "repos_url": "https://api.github.com/users/SimonBoothroyd/repos", "events_url": "https://api.github.com/users/SimonBoothroyd/events{/privacy}", "received_events_url": "https://api.github.com/users/SimonBoothroyd/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/hgrecco/pint/milestones/9", "html_url": "https://github.com/hgrecco/pint/milestone/9", "labels_url": "https://api.github.com/repos/hgrecco/pint/milestones/9/labels", "id": 4974941, "node_id": "MDk6TWlsZXN0b25lNDk3NDk0MQ==", "number": 9, "title": "0.11", "description": "", "creator": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 13, "state": "closed", "created_at": "2020-01-06T04:21:02Z", "updated_at": "2020-02-19T22:43:39Z", "due_on": "2020-02-18T08:00:00Z", "closed_at": "2020-02-19T22:43:39Z"}, "comments": 4, "created_at": "2020-02-06T18:00:04Z", "updated_at": "2020-06-03T12:38:01Z", "closed_at": "2020-02-19T16:34:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "Pickling and un-pickling a quantity will cause type coercion between the dynamic `Quantity` class defined by a `UnitRegistry` and the global `Quantity` class. \r\n\r\nThis leads to exceptions being raised when comparing quantities which have been pickled with those that haven't:\r\n\r\n## Steps to Reproduce the Problem\r\n\r\n```\r\nimport pint\r\nimport pickle\r\n\r\nureg = pint.UnitRegistry()\r\npint.set_application_registry(ureg)\r\n\r\nx = 1.0 * ureg.kelvin\r\ny = pickle.loads(pickle.dumps(x))\r\n\r\nz = x > y\r\n```\r\n(tested with `pint ==0.10.1`)\r\n\r\n## Exception Raised\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"xxx/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3331, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-2-1f849a21d3d1>\", line 10, in <module>\r\n    z = x > y\r\n  File \"xxx/python3.7/site-packages/pint/quantity.py\", line 1484, in <lambda>\r\n    __gt__ = lambda self, other: self.compare(other, op=operator.gt)\r\n  File \"xxx/python3.7/site-packages/pint/quantity.py\", line 106, in wrapped\r\n    result = f(self, *args, **kwargs)\r\n  File \"xxx/python3.7/site-packages/pint/quantity.py\", line 1471, in compare\r\n    raise ValueError(\"Cannot compare Quantity and {}\".format(type(other)))\r\nValueError: Cannot compare Quantity and <class 'pint.quantity.Quantity'>\r\n```", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/1017/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/1017/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/992", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/992/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/992/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/992/events", "html_url": "https://github.com/hgrecco/pint/issues/992", "id": 551513073, "node_id": "MDU6SXNzdWU1NTE1MTMwNzM=", "number": 992, "title": "non-quantity constant_values parameter to pad", "user": {"login": "keewis", "id": 14808389, "node_id": "MDQ6VXNlcjE0ODA4Mzg5", "avatar_url": "https://avatars.githubusercontent.com/u/14808389?v=4", "gravatar_id": "", "url": "https://api.github.com/users/keewis", "html_url": "https://github.com/keewis", "followers_url": "https://api.github.com/users/keewis/followers", "following_url": "https://api.github.com/users/keewis/following{/other_user}", "gists_url": "https://api.github.com/users/keewis/gists{/gist_id}", "starred_url": "https://api.github.com/users/keewis/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/keewis/subscriptions", "organizations_url": "https://api.github.com/users/keewis/orgs", "repos_url": "https://api.github.com/users/keewis/repos", "events_url": "https://api.github.com/users/keewis/events{/privacy}", "received_events_url": "https://api.github.com/users/keewis/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 1712992969, "node_id": "MDU6TGFiZWwxNzEyOTkyOTY5", "url": "https://api.github.com/repos/hgrecco/pint/labels/numpy", "name": "numpy", "color": "e8a4e6", "default": false, "description": "Numpy related bug/enhancement"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-01-17T16:30:41Z", "updated_at": "2020-01-22T05:28:06Z", "closed_at": "2020-01-22T05:28:06Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Passing non-quantity parameters to `np.pad` in `constant` mode results in behaviour different from passing `dimensionless` quantities:\r\n```python\r\nIn [1]: import numpy as np \r\n   ...: import pint \r\n   ...: ureg = pint.UnitRegistry()\r\n\r\nIn [2]: a = np.arange(5) * ureg.m\r\n\r\nIn [3]: np.pad(a, (2, 4), mode=\"constant\", constant_values=4)                                                                                                                                                                   \r\nOut[3]: array([4, 4, 0, 1, 2, 3, 4, 4, 4, 4, 4]) <Unit('meter')>\r\n\r\nIn [4]: np.pad(a, (2, 4), mode=\"constant\", constant_values=4 * ureg.dimensionless)                                                                                                                                              \r\nDimensionalityError: Cannot convert from 'dimensionless' (dimensionless) to 'meter' ([length])\r\n```\r\nI'd expect `[3]` and `[4]` to be equivalent, but one of the checks in `test_pad` seems to expect the current behaviour so I'm not sure if this is a misconception on my part.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/992/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/992/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/974", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/974/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/974/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/974/events", "html_url": "https://github.com/hgrecco/pint/issues/974", "id": 546591455, "node_id": "MDU6SXNzdWU1NDY1OTE0NTU=", "number": 974, "title": "TypeError: __array__() takes 1 positional argument but 2 were given", "user": {"login": "dopplershift", "id": 221526, "node_id": "MDQ6VXNlcjIyMTUyNg==", "avatar_url": "https://avatars.githubusercontent.com/u/221526?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dopplershift", "html_url": "https://github.com/dopplershift", "followers_url": "https://api.github.com/users/dopplershift/followers", "following_url": "https://api.github.com/users/dopplershift/following{/other_user}", "gists_url": "https://api.github.com/users/dopplershift/gists{/gist_id}", "starred_url": "https://api.github.com/users/dopplershift/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dopplershift/subscriptions", "organizations_url": "https://api.github.com/users/dopplershift/orgs", "repos_url": "https://api.github.com/users/dopplershift/repos", "events_url": "https://api.github.com/users/dopplershift/events{/privacy}", "received_events_url": "https://api.github.com/users/dopplershift/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2020-01-08T01:16:21Z", "updated_at": "2020-01-08T18:30:51Z", "closed_at": "2020-01-08T02:49:22Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Looks like a bug crept into 0.10 when `PINT_ARRAY_PROTOCOL_FALLBACK` is `'0'`:\r\n```python\r\nimport os\r\nos.environ['PINT_ARRAY_PROTOCOL_FALLBACK'] = '0'\r\n\r\nimport numpy as np\r\nimport pint\r\n\r\nq = pint.Quantity(np.arange(3, dtype=np.float32), 'm')\r\nnp.array(q) # OK\r\nnp.array(q, dtype=np.float64) # Error\r\n```\r\nThe last one yields:\r\n```pytb\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-5-ba6cd2ac8160> in <module>\r\n      8 np.array(q)\r\n      9 \r\n---> 10 np.array(q, dtype=np.float64)\r\n\r\nTypeError: __array__() takes 1 positional argument but 2 were given\r\n```\r\n\r\nI think that's because the `__array__` implementation does not accept any args:\r\nhttps://github.com/hgrecco/pint/blob/a70be489c46c03ca15c2832a308a56a556270461/pint/quantity.py#L1554-L1560\r\n\r\nPR with tests incoming...\r\n\r\n(attn: @jthielen)", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/974/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/974/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/973", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/973/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/973/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/973/events", "html_url": "https://github.com/hgrecco/pint/issues/973", "id": 546171544, "node_id": "MDU6SXNzdWU1NDYxNzE1NDQ=", "number": 973, "title": "IndexError on assigning units to empty Numpy array (Pint 0.10)", "user": {"login": "rebeccafair", "id": 18187336, "node_id": "MDQ6VXNlcjE4MTg3MzM2", "avatar_url": "https://avatars.githubusercontent.com/u/18187336?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rebeccafair", "html_url": "https://github.com/rebeccafair", "followers_url": "https://api.github.com/users/rebeccafair/followers", "following_url": "https://api.github.com/users/rebeccafair/following{/other_user}", "gists_url": "https://api.github.com/users/rebeccafair/gists{/gist_id}", "starred_url": "https://api.github.com/users/rebeccafair/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rebeccafair/subscriptions", "organizations_url": "https://api.github.com/users/rebeccafair/orgs", "repos_url": "https://api.github.com/users/rebeccafair/repos", "events_url": "https://api.github.com/users/rebeccafair/events{/privacy}", "received_events_url": "https://api.github.com/users/rebeccafair/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/hgrecco/pint/milestones/9", "html_url": "https://github.com/hgrecco/pint/milestone/9", "labels_url": "https://api.github.com/repos/hgrecco/pint/milestones/9/labels", "id": 4974941, "node_id": "MDk6TWlsZXN0b25lNDk3NDk0MQ==", "number": 9, "title": "0.11", "description": "", "creator": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 13, "state": "closed", "created_at": "2020-01-06T04:21:02Z", "updated_at": "2020-02-19T22:43:39Z", "due_on": "2020-02-18T08:00:00Z", "closed_at": "2020-02-19T22:43:39Z"}, "comments": 6, "created_at": "2020-01-07T09:23:22Z", "updated_at": "2020-01-08T09:56:49Z", "closed_at": "2020-01-08T04:36:40Z", "author_association": "NONE", "active_lock_reason": null, "body": "Since the 0.10 update if I try to assign units to an empty array, I get an IndexError\r\n\r\n```\r\n>>> import numpy as np\r\n>>> import pint\r\n>>> ureg = pint.UnitRegistry()\r\n>>> x = np.array([])\r\n>>> x*ureg('kg')\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Users\\mll13652\\AppData\\Local\\conda\\conda\\envs\\py37\\lib\\site-packages\\pint\\quantity.py\", line 1507, in __array_ufunc__\r\n    return numpy_wrap(\"ufunc\", ufunc, inputs, kwargs, types)\r\n  File \"C:\\Users\\mll13652\\AppData\\Local\\conda\\conda\\envs\\py37\\lib\\site-packages\\pint\\numpy_func.py\", line 888, in numpy_wrap\r\n    return handled[name](*args, **kwargs)\r\n  File \"C:\\Users\\mll13652\\AppData\\Local\\conda\\conda\\envs\\py37\\lib\\site-packages\\pint\\numpy_func.py\", line 268, in implementation\r\n    first_input_units = _get_first_input_units(args, kwargs)\r\n  File \"C:\\Users\\mll13652\\AppData\\Local\\conda\\conda\\envs\\py37\\lib\\site-packages\\pint\\numpy_func.py\", line 69, in _get_first_input_units\r\n    return arg[0].units\r\nIndexError: index 0 is out of bounds for axis 0 with size 0\r\n```\r\n\r\nAfter looking into it a bit more it seems that in `_get_first_input_units`, `_is_quantity_sequence()` incorrectly returns `True` for empty arrays as the final check:\r\n```\r\nall(_is_quantity(item) for item in obj)\r\n```\r\nreturns `True` for empty arrays.\r\n\r\nOne possible fix would be to get `sized` to also check for zero length and return `False`, preventing the check from getting to the above line, and I'd be happy enough to make a PR for this\r\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/973/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/973/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/960", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/960/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/960/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/960/events", "html_url": "https://github.com/hgrecco/pint/issues/960", "id": 543043000, "node_id": "MDU6SXNzdWU1NDMwNDMwMDA=", "number": 960, "title": "`to_compact` handles prefixed units incorrectly.", "user": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-12-28T02:02:41Z", "updated_at": "2020-01-22T05:42:28Z", "closed_at": "2020-01-22T05:42:28Z", "author_association": "OWNER", "active_lock_reason": null, "body": "There is a bug in `to_compact` handling the `unit` argument\r\n\r\n```python\r\n>>> (1 * ureg.nanometer).to_compact(ureg.micrometer)\r\n<Quantity(1.0000000000000002, 'millimicrometer')>\r\n```\r\n\r\nwhen the unit is prefixed", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/960/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/960/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/532", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/532/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/532/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/532/events", "html_url": "https://github.com/hgrecco/pint/issues/532", "id": 238901394, "node_id": "MDU6SXNzdWUyMzg5MDEzOTQ=", "number": 532, "title": "ureg.check fails to check dimensionless quantity", "user": {"login": "AntoineGX", "id": 24521143, "node_id": "MDQ6VXNlcjI0NTIxMTQz", "avatar_url": "https://avatars.githubusercontent.com/u/24521143?v=4", "gravatar_id": "", "url": "https://api.github.com/users/AntoineGX", "html_url": "https://github.com/AntoineGX", "followers_url": "https://api.github.com/users/AntoineGX/followers", "following_url": "https://api.github.com/users/AntoineGX/following{/other_user}", "gists_url": "https://api.github.com/users/AntoineGX/gists{/gist_id}", "starred_url": "https://api.github.com/users/AntoineGX/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/AntoineGX/subscriptions", "organizations_url": "https://api.github.com/users/AntoineGX/orgs", "repos_url": "https://api.github.com/users/AntoineGX/repos", "events_url": "https://api.github.com/users/AntoineGX/events{/privacy}", "received_events_url": "https://api.github.com/users/AntoineGX/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-06-27T16:00:33Z", "updated_at": "2017-06-28T01:27:41Z", "closed_at": "2017-06-28T01:27:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\nThank you for this useful package.\r\n\r\nI think there is an issue with the quantity type checking decorator. It doesn't raise any exception when the passed quantity is not dimensionless as expected.\r\n\r\nConsider the following example:\r\n```\r\nimport pint\r\nureg = pint.UnitRegistry()\r\n@ureg.check(ureg(''))\r\ndef f(x):\r\n    return 2*x\r\nprint(f(ureg.Quantity(1, '')))\r\nprint(f(ureg.Quantity(1, 'm')))\r\n```\r\nThe first call to \"f\" is correct, the second one should raise an exception but it doesn't happen.\r\n\r\nThanks to take some time to analyze this issue.\r\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/532/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/532/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/512", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/512/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/512/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/512/events", "html_url": "https://github.com/hgrecco/pint/issues/512", "id": 229557618, "node_id": "MDU6SXNzdWUyMjk1NTc2MTg=", "number": 512, "title": "Numpy support issue in Jupyter", "user": {"login": "rbeucher", "id": 3680918, "node_id": "MDQ6VXNlcjM2ODA5MTg=", "avatar_url": "https://avatars.githubusercontent.com/u/3680918?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rbeucher", "html_url": "https://github.com/rbeucher", "followers_url": "https://api.github.com/users/rbeucher/followers", "following_url": "https://api.github.com/users/rbeucher/following{/other_user}", "gists_url": "https://api.github.com/users/rbeucher/gists{/gist_id}", "starred_url": "https://api.github.com/users/rbeucher/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rbeucher/subscriptions", "organizations_url": "https://api.github.com/users/rbeucher/orgs", "repos_url": "https://api.github.com/users/rbeucher/repos", "events_url": "https://api.github.com/users/rbeucher/events{/privacy}", "received_events_url": "https://api.github.com/users/rbeucher/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-05-18T05:18:02Z", "updated_at": "2017-05-26T03:05:04Z", "closed_at": "2017-05-26T03:05:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am having some issues with numpy arrays since yesterday.\r\n\r\nnumpy version is 1.12.1\r\npint version is 0.8 (from pip)\r\npython 2.7.13\r\n\r\nMinimal example:\r\n\r\n```\r\nimport pint\r\nimport numpy as np\r\n\r\nu = pint.UnitRegistry()\r\nnp.array([1.0,2.0]) * u.metre\r\n```\r\nPint returns a TypeError\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n/usr/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)\r\n    309             method = get_real_method(obj, self.print_method)\r\n    310             if method is not None:\r\n--> 311                 return method()\r\n    312             return None\r\n    313         else:\r\n\r\n/usr/lib/python2.7/site-packages/pint/quantity.pyc in _repr_html_(self)\r\n    193     # IPython related code\r\n    194     def _repr_html_(self):\r\n--> 195         return self.__format__('H')\r\n    196 \r\n    197     def _repr_latex_(self):\r\n\r\n/usr/lib/python2.7/site-packages/pint/quantity.pyc in __format__(self, spec)\r\n    157                 # this is required to have the magnitude and unit in the same line\r\n    158                 allf = r'\\[{0} {1}\\]'\r\n--> 159                 parts = ndarray_to_latex_parts(obj.magnitude, mspec)\r\n    160 \r\n    161                 if len(parts) > 1:\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in ndarray_to_latex_parts(ndarr, fmtfun, dim)\r\n    294 \r\n    295     if ndarr.ndim == 1:\r\n--> 296         return [vector_to_latex(ndarr, fmtfun)]\r\n    297     if ndarr.ndim == 2:\r\n    298         return [matrix_to_latex(ndarr, fmtfun)]\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in vector_to_latex(vec, fmtfun)\r\n    276 \r\n    277 def vector_to_latex(vec, fmtfun=lambda x: format(x, '.2f')):\r\n--> 278     return matrix_to_latex([vec], fmtfun)\r\n    279 \r\n    280 \r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in matrix_to_latex(matrix, fmtfun)\r\n    283 \r\n    284     for row in matrix:\r\n--> 285         ret += [' & '.join(fmtfun(f) for f in row)]\r\n    286 \r\n    287     return r'\\begin{pmatrix}%s\\end{pmatrix}' % '\\\\\\\\ \\n'.join(ret)\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in <genexpr>((f,))\r\n    283 \r\n    284     for row in matrix:\r\n--> 285         ret += [' & '.join(fmtfun(f) for f in row)]\r\n    286 \r\n    287     return r'\\begin{pmatrix}%s\\end{pmatrix}' % '\\\\\\\\ \\n'.join(ret)\r\n\r\nTypeError: 'unicode' object is not callable\r\n\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n/usr/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)\r\n    309             method = get_real_method(obj, self.print_method)\r\n    310             if method is not None:\r\n--> 311                 return method()\r\n    312             return None\r\n    313         else:\r\n\r\n/usr/lib/python2.7/site-packages/pint/quantity.pyc in _repr_latex_(self)\r\n    196 \r\n    197     def _repr_latex_(self):\r\n--> 198         return \"$\" + self.__format__('L') + \"$\"\r\n    199 \r\n    200     @property\r\n\r\n/usr/lib/python2.7/site-packages/pint/quantity.pyc in __format__(self, spec)\r\n    153         if isinstance(self.magnitude, ndarray):\r\n    154             if 'L' in spec:\r\n--> 155                 mstr = ndarray_to_latex(obj.magnitude, mspec)\r\n    156             elif 'H' in spec:\r\n    157                 # this is required to have the magnitude and unit in the same line\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in ndarray_to_latex(ndarr, fmtfun, dim)\r\n    311 \r\n    312 def ndarray_to_latex(ndarr, fmtfun=lambda x: format(x, '.2f'), dim=()):\r\n--> 313         return '\\n'.join(ndarray_to_latex_parts(ndarr, fmtfun, dim))\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in ndarray_to_latex_parts(ndarr, fmtfun, dim)\r\n    294 \r\n    295     if ndarr.ndim == 1:\r\n--> 296         return [vector_to_latex(ndarr, fmtfun)]\r\n    297     if ndarr.ndim == 2:\r\n    298         return [matrix_to_latex(ndarr, fmtfun)]\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in vector_to_latex(vec, fmtfun)\r\n    276 \r\n    277 def vector_to_latex(vec, fmtfun=lambda x: format(x, '.2f')):\r\n--> 278     return matrix_to_latex([vec], fmtfun)\r\n    279 \r\n    280 \r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in matrix_to_latex(matrix, fmtfun)\r\n    283 \r\n    284     for row in matrix:\r\n--> 285         ret += [' & '.join(fmtfun(f) for f in row)]\r\n    286 \r\n    287     return r'\\begin{pmatrix}%s\\end{pmatrix}' % '\\\\\\\\ \\n'.join(ret)\r\n\r\n/usr/lib/python2.7/site-packages/pint/formatting.pyc in <genexpr>((f,))\r\n    283 \r\n    284     for row in matrix:\r\n--> 285         ret += [' & '.join(fmtfun(f) for f in row)]\r\n    286 \r\n    287     return r'\\begin{pmatrix}%s\\end{pmatrix}' % '\\\\\\\\ \\n'.join(ret)\r\n\r\nTypeError: 'unicode' object is not callable\r\n\r\nOut[15]:\r\n<Quantity([ 1.  2.], 'meter')>\r\n```", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/512/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/512/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/509", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/509/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/509/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/509/events", "html_url": "https://github.com/hgrecco/pint/issues/509", "id": 228975759, "node_id": "MDU6SXNzdWUyMjg5NzU3NTk=", "number": 509, "title": "Mutated type in Quantity", "user": {"login": "cmft", "id": 6168722, "node_id": "MDQ6VXNlcjYxNjg3MjI=", "avatar_url": "https://avatars.githubusercontent.com/u/6168722?v=4", "gravatar_id": "", "url": "https://api.github.com/users/cmft", "html_url": "https://github.com/cmft", "followers_url": "https://api.github.com/users/cmft/followers", "following_url": "https://api.github.com/users/cmft/following{/other_user}", "gists_url": "https://api.github.com/users/cmft/gists{/gist_id}", "starred_url": "https://api.github.com/users/cmft/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/cmft/subscriptions", "organizations_url": "https://api.github.com/users/cmft/orgs", "repos_url": "https://api.github.com/users/cmft/repos", "events_url": "https://api.github.com/users/cmft/events{/privacy}", "received_events_url": "https://api.github.com/users/cmft/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 3, "created_at": "2017-05-16T09:53:42Z", "updated_at": "2019-12-24T21:01:18Z", "closed_at": "2019-12-24T21:01:18Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "If I do a `np.shape` over a Quantity, the operation mutates the type of the `.magnitude`\r\n\r\nSee the example below :\r\n\r\n``` \r\n#pint.__version__  ('0.8')\r\n#numpy.__version__ ('1.10.1')\r\n\r\nimport pint\r\nimport numpy as np\r\n\r\nureg = pint.UnitRegistry()\r\nq = ureg.Quantity(1)\r\nprint type(q.magnitude) # <type 'int'>\r\nnp.shape(q) #Out[6]: ()\r\nprint type(q.magnitude) # <type 'numpy.ndarray'>\r\n```", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/509/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/509/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/483", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/483/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/483/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/483/events", "html_url": "https://github.com/hgrecco/pint/issues/483", "id": 211339652, "node_id": "MDU6SXNzdWUyMTEzMzk2NTI=", "number": 483, "title": "Dimensionless base with dimensionless exponent: Cannot convert from 'dimensionless' to 'dimensionless'", "user": {"login": "gerritholl", "id": 500246, "node_id": "MDQ6VXNlcjUwMDI0Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/500246?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gerritholl", "html_url": "https://github.com/gerritholl", "followers_url": "https://api.github.com/users/gerritholl/followers", "following_url": "https://api.github.com/users/gerritholl/following{/other_user}", "gists_url": "https://api.github.com/users/gerritholl/gists{/gist_id}", "starred_url": "https://api.github.com/users/gerritholl/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gerritholl/subscriptions", "organizations_url": "https://api.github.com/users/gerritholl/orgs", "repos_url": "https://api.github.com/users/gerritholl/repos", "events_url": "https://api.github.com/users/gerritholl/events{/privacy}", "received_events_url": "https://api.github.com/users/gerritholl/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/hgrecco/pint/milestones/7", "html_url": "https://github.com/hgrecco/pint/milestone/7", "labels_url": "https://api.github.com/repos/hgrecco/pint/milestones/7/labels", "id": 1574103, "node_id": "MDk6TWlsZXN0b25lMTU3NDEwMw==", "number": 7, "title": "0.8", "description": "", "creator": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 5, "state": "closed", "created_at": "2016-02-10T03:45:48Z", "updated_at": "2017-10-20T23:51:58Z", "due_on": "2017-04-15T07:00:00Z", "closed_at": "2017-10-20T23:51:58Z"}, "comments": 0, "created_at": "2017-03-02T09:48:44Z", "updated_at": "2017-04-16T03:04:34Z", "closed_at": "2017-04-16T03:04:34Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Raising the power to a dimensionless array gives a rather confusing error message:\r\n\r\n```\r\nIn [3]: q = ureg.Quantity(array([1, 2, 3]), \"dimensionless\")\r\n\r\nIn [4]: q**q\r\n---------------------------------------------------------------------------\r\nDimensionalityError                       Traceback (most recent call last)\r\n<ipython-input-4-03e332c95cf3> in <module>()\r\n----> 1 q**q\r\n\r\n/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/pint/quantity.py in __pow__(self, other)\r\n    889                 #  len(array) quantities of len(set(array)) different units\r\n    890                 if np.size(other) > 1:\r\n--> 891                     raise DimensionalityError(self._units, 'dimensionless')\r\n    892 \r\n    893             new_self = self\r\n\r\nDimensionalityError: Cannot convert from 'dimensionless' to 'dimensionless'\r\n\r\nIn [9]: 2**q\r\n---------------------------------------------------------------------------\r\nDimensionalityError                       Traceback (most recent call last)\r\n<ipython-input-9-91a1970227e2> in <module>()\r\n----> 1 2**q\r\n\r\n/dev/shm/gerrit/venv/stable-3.5/lib/python3.5/site-packages/pint/quantity.py in __rpow__(self, other)\r\n    923             if isinstance(self._magnitude, ndarray):\r\n    924                 if np.size(self._magnitude) > 1:\r\n--> 925                     raise DimensionalityError(self._units, 'dimensionless')\r\n    926             new_self = self.to_root_units()\r\n    927             return other**new_self._magnitude\r\n\r\nDimensionalityError: Cannot convert from 'dimensionless' to 'dimensionless'\r\n\r\n```\r\n\r\nI can see why I can't take the exponent of a dimensioned quantity, but it could give a more helpful error message.  And if both base and exponent are dimensionless there should not be any objection to carry out the operation.", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/483/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/483/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/468", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/468/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/468/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/468/events", "html_url": "https://github.com/hgrecco/pint/issues/468", "id": 193235350, "node_id": "MDU6SXNzdWUxOTMyMzUzNTA=", "number": 468, "title": "ureg.wraps not returning correct units", "user": {"login": "alexfeld", "id": 17606949, "node_id": "MDQ6VXNlcjE3NjA2OTQ5", "avatar_url": "https://avatars.githubusercontent.com/u/17606949?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alexfeld", "html_url": "https://github.com/alexfeld", "followers_url": "https://api.github.com/users/alexfeld/followers", "following_url": "https://api.github.com/users/alexfeld/following{/other_user}", "gists_url": "https://api.github.com/users/alexfeld/gists{/gist_id}", "starred_url": "https://api.github.com/users/alexfeld/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alexfeld/subscriptions", "organizations_url": "https://api.github.com/users/alexfeld/orgs", "repos_url": "https://api.github.com/users/alexfeld/repos", "events_url": "https://api.github.com/users/alexfeld/events{/privacy}", "received_events_url": "https://api.github.com/users/alexfeld/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/hgrecco/pint/milestones/7", "html_url": "https://github.com/hgrecco/pint/milestone/7", "labels_url": "https://api.github.com/repos/hgrecco/pint/milestones/7/labels", "id": 1574103, "node_id": "MDk6TWlsZXN0b25lMTU3NDEwMw==", "number": 7, "title": "0.8", "description": "", "creator": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 5, "state": "closed", "created_at": "2016-02-10T03:45:48Z", "updated_at": "2017-10-20T23:51:58Z", "due_on": "2017-04-15T07:00:00Z", "closed_at": "2017-10-20T23:51:58Z"}, "comments": 1, "created_at": "2016-12-02T22:40:23Z", "updated_at": "2017-04-16T03:05:32Z", "closed_at": "2017-04-16T03:05:32Z", "author_association": "NONE", "active_lock_reason": null, "body": "Before, I was able to abbreviate return units, e.g.\r\n ```python\r\n@ureg.wraps(('kg'), 'meter')\r\ndef f(x):\r\n    return x\r\n\r\nx = Q_(1., 'meter')\r\ny = f(x)\r\nz = x*y\r\nprint z.units\r\n```\r\n\r\nBefore, the 'kg' was automatically converted to 'kilograms' by `pint`. Now, after updating today from the master branch, if I try the above code I get a `KeyError: u'kg'`", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/468/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/468/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/452", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/452/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/452/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/452/events", "html_url": "https://github.com/hgrecco/pint/issues/452", "id": 187588634, "node_id": "MDU6SXNzdWUxODc1ODg2MzQ=", "number": 452, "title": "Decimal conversion with offset", "user": {"login": "txxia", "id": 8399710, "node_id": "MDQ6VXNlcjgzOTk3MTA=", "avatar_url": "https://avatars.githubusercontent.com/u/8399710?v=4", "gravatar_id": "", "url": "https://api.github.com/users/txxia", "html_url": "https://github.com/txxia", "followers_url": "https://api.github.com/users/txxia/followers", "following_url": "https://api.github.com/users/txxia/following{/other_user}", "gists_url": "https://api.github.com/users/txxia/gists{/gist_id}", "starred_url": "https://api.github.com/users/txxia/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/txxia/subscriptions", "organizations_url": "https://api.github.com/users/txxia/orgs", "repos_url": "https://api.github.com/users/txxia/repos", "events_url": "https://api.github.com/users/txxia/events{/privacy}", "received_events_url": "https://api.github.com/users/txxia/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2016-11-06T20:57:59Z", "updated_at": "2021-05-26T12:54:25Z", "closed_at": "2021-05-26T12:54:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\nI started using pint as it supports Decimal types, but seems like it's not handled in conversion with offset.\r\n\r\nHere is an example:\r\n```python\r\n>>> from pint import UnitRegistry\r\n>>> from decimal import Decimal\r\n>>> UR = UnitRegistry()\r\n>>> q = UR.Quantity(Decimal('0'), 'K')\r\n>>> q\r\n<Quantity(0, 'kelvin')>\r\n>>> q.to('celsius')\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Program Files (x86)\\Python35-32\\lib\\site-packages\\pint\\quantity.py\", line 263, in to\r\n    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)\r\n  File \"C:\\Program Files (x86)\\Python35-32\\lib\\site-packages\\pint\\quantity.py\", line 231, in _convert_magnitude_not_inplace\r\n    return self._REGISTRY.convert(self._magnitude, self._units, other)\r\n  File \"C:\\Program Files (x86)\\Python35-32\\lib\\site-packages\\pint\\unit.py\", line 1026, in convert\r\n    return self._convert(value, src, dst, inplace)\r\n  File \"C:\\Program Files (x86)\\Python35-32\\lib\\site-packages\\pint\\unit.py\", line 1134, in _convert\r\n    value = self._units[u].converter.from_reference(value, inplace)\r\n  File \"C:\\Program Files (x86)\\Python35-32\\lib\\site-packages\\pint\\converters.py\", line 80, in from_reference\r\n    value = (value - self.offset) / self.scale\r\nTypeError: unsupported operand type(s) for -: 'decimal.Decimal' and 'float'\r\n```", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/452/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/452/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/434", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/434/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/434/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/434/events", "html_url": "https://github.com/hgrecco/pint/issues/434", "id": 177007309, "node_id": "MDU6SXNzdWUxNzcwMDczMDk=", "number": 434, "title": "Comparison is valid in places that arithmetic is not", "user": {"login": "eric-wieser", "id": 425260, "node_id": "MDQ6VXNlcjQyNTI2MA==", "avatar_url": "https://avatars.githubusercontent.com/u/425260?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eric-wieser", "html_url": "https://github.com/eric-wieser", "followers_url": "https://api.github.com/users/eric-wieser/followers", "following_url": "https://api.github.com/users/eric-wieser/following{/other_user}", "gists_url": "https://api.github.com/users/eric-wieser/gists{/gist_id}", "starred_url": "https://api.github.com/users/eric-wieser/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eric-wieser/subscriptions", "organizations_url": "https://api.github.com/users/eric-wieser/orgs", "repos_url": "https://api.github.com/users/eric-wieser/repos", "events_url": "https://api.github.com/users/eric-wieser/events{/privacy}", "received_events_url": "https://api.github.com/users/eric-wieser/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-09-14T20:08:32Z", "updated_at": "2022-01-24T22:14:00Z", "closed_at": "2022-01-24T22:14:00Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Compare:\n\n```\n>>> u1 = pint.UnitRegistry()\n>>> u2 = pint.UnitRegistry()\n>>> 1*u1.m == 1*u2.m\nTrue\n>>> (1*u1.m - 1*u2.m).m == 0\nValueError: Cannot operate with Quantity and Quantity of different registries.\n```\n\nIt seems weird to allow comparison but not arithmetic\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/434/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/434/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/174", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/174/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/174/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/174/events", "html_url": "https://github.com/hgrecco/pint/issues/174", "id": 39134924, "node_id": "MDU6SXNzdWUzOTEzNDkyNA==", "number": 174, "title": "arg() is malformed string with multiple-parameter context", "user": {"login": "rkingsbury", "id": 1908695, "node_id": "MDQ6VXNlcjE5MDg2OTU=", "avatar_url": "https://avatars.githubusercontent.com/u/1908695?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rkingsbury", "html_url": "https://github.com/rkingsbury", "followers_url": "https://api.github.com/users/rkingsbury/followers", "following_url": "https://api.github.com/users/rkingsbury/following{/other_user}", "gists_url": "https://api.github.com/users/rkingsbury/gists{/gist_id}", "starred_url": "https://api.github.com/users/rkingsbury/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rkingsbury/subscriptions", "organizations_url": "https://api.github.com/users/rkingsbury/orgs", "repos_url": "https://api.github.com/users/rkingsbury/repos", "events_url": "https://api.github.com/users/rkingsbury/events{/privacy}", "received_events_url": "https://api.github.com/users/rkingsbury/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2014-07-30T20:42:45Z", "updated_at": "2014-07-30T23:22:46Z", "closed_at": "2014-07-30T22:09:36Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello,\nI'm trying to define a multiple-parameter context to handle concentration calculations for solution chemistry. It seems that including multiple parameters in my context definition file triggers an error:\n\n'While opening pint_custom_units.txt complex() arg is a malformed string'\n\nThe line that triggers the error is:\n'@context(mw=0,volume=0,solvent_mass=0) chemistry = chem'\n\nIf I define only one parameter, the error is gone:\n'@context(mw=0) chemistry = chem'\n\nUnless I'm misinterpeting the documentation, this smells like a bug. Any help would be appreciated.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/174/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/174/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/170", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/170/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/170/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/170/events", "html_url": "https://github.com/hgrecco/pint/issues/170", "id": 37497221, "node_id": "MDU6SXNzdWUzNzQ5NzIyMQ==", "number": 170, "title": "Dimensionless quantities behave unexpectedly when cast to int", "user": {"login": "natezb", "id": 3268059, "node_id": "MDQ6VXNlcjMyNjgwNTk=", "avatar_url": "https://avatars.githubusercontent.com/u/3268059?v=4", "gravatar_id": "", "url": "https://api.github.com/users/natezb", "html_url": "https://github.com/natezb", "followers_url": "https://api.github.com/users/natezb/followers", "following_url": "https://api.github.com/users/natezb/following{/other_user}", "gists_url": "https://api.github.com/users/natezb/gists{/gist_id}", "starred_url": "https://api.github.com/users/natezb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/natezb/subscriptions", "organizations_url": "https://api.github.com/users/natezb/orgs", "repos_url": "https://api.github.com/users/natezb/repos", "events_url": "https://api.github.com/users/natezb/events{/privacy}", "received_events_url": "https://api.github.com/users/natezb/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2014-07-09T18:57:05Z", "updated_at": "2014-07-10T16:57:13Z", "closed_at": "2014-07-10T16:57:13Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "This is a variant of the old bug #54. It seems that the issue was fixed for floats, but casting to an int still causes issues. For example:\n\n```\n>>> q = Q_('1 kHz')/Q_('100 Hz')\n>>> float(q)  # Behaves as expected\n10.0\n>>> int(q)  # Behaves unexpectedly\n0\n```\n\nPresumably, adding an `__int__` method will fix this, though I haven't yet tried it.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/170/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/170/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/160", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/160/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/160/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/160/events", "html_url": "https://github.com/hgrecco/pint/issues/160", "id": 35744322, "node_id": "MDU6SXNzdWUzNTc0NDMyMg==", "number": 160, "title": "UnitsContainer print", "user": {"login": "romarro", "id": 7783693, "node_id": "MDQ6VXNlcjc3ODM2OTM=", "avatar_url": "https://avatars.githubusercontent.com/u/7783693?v=4", "gravatar_id": "", "url": "https://api.github.com/users/romarro", "html_url": "https://github.com/romarro", "followers_url": "https://api.github.com/users/romarro/followers", "following_url": "https://api.github.com/users/romarro/following{/other_user}", "gists_url": "https://api.github.com/users/romarro/gists{/gist_id}", "starred_url": "https://api.github.com/users/romarro/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/romarro/subscriptions", "organizations_url": "https://api.github.com/users/romarro/orgs", "repos_url": "https://api.github.com/users/romarro/repos", "events_url": "https://api.github.com/users/romarro/events{/privacy}", "received_events_url": "https://api.github.com/users/romarro/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2014-06-15T07:32:57Z", "updated_at": "2015-02-06T20:33:55Z", "closed_at": "2015-02-06T20:33:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi I want to print only the units of a quantity (for a label in a plot). But it doesn't print the abbreviated units  even if I am formatting it with ~\nhere is the code:\n\n> > > from **init** import um,Q_\n> > > x=125.3*um['l/s']\n> > > print x\n> > > 125.3 l/s\n> > > x.units\n> > > <UnitsContainer({'liter': 1.0, 'second': -1.0})>\n> > > print x.units\n> > > liter / second\n> > > print '{:~}'.format(x.units)\n> > > liter / second\n> > > print '{:~L}'.format(x.units)\n> > > \\frac{liter}{second}\n\nBut with latex formatting works\nis there a workaround?\n\nThanks for help \n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/160/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/160/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/87", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/87/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/87/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/87/events", "html_url": "https://github.com/hgrecco/pint/issues/87", "id": 25431123, "node_id": "MDU6SXNzdWUyNTQzMTEyMw==", "number": 87, "title": "'R' definied as both constant and unit", "user": {"login": "rkingsbury", "id": 1908695, "node_id": "MDQ6VXNlcjE5MDg2OTU=", "avatar_url": "https://avatars.githubusercontent.com/u/1908695?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rkingsbury", "html_url": "https://github.com/rkingsbury", "followers_url": "https://api.github.com/users/rkingsbury/followers", "following_url": "https://api.github.com/users/rkingsbury/following{/other_user}", "gists_url": "https://api.github.com/users/rkingsbury/gists{/gist_id}", "starred_url": "https://api.github.com/users/rkingsbury/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rkingsbury/subscriptions", "organizations_url": "https://api.github.com/users/rkingsbury/orgs", "repos_url": "https://api.github.com/users/rkingsbury/repos", "events_url": "https://api.github.com/users/rkingsbury/events{/privacy}", "received_events_url": "https://api.github.com/users/rkingsbury/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-01-10T23:44:45Z", "updated_at": "2014-01-11T13:32:29Z", "closed_at": "2014-01-11T13:32:29Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "First off thank you hgrecco for this fantastic package. I was about to set out writing something similar, when I realized that this does exactly what I was looking for!\n\nI may have found an issue though. I'm trying to access the value of the molar gas constant stored in pint. (Forgive me if this isn't the correct method, I couldn't find anything in the documentation about accessing constants). And I realized that the name 'R' is used to refer both to the molar_gas_constant in constants_en.txt AND to the unit 'roentgen' in default_en.txt.\n\n```\n>>> unit=UnitRegistry()\n>>> unit.R\n<Quantity(1, 'roentgen')>\n>>> unit.k\n<Quantity(1, 'boltzmann_constant')>\n```\n\nI believe there should be separate names for each.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/87/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/87/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/85", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/85/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/85/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/85/events", "html_url": "https://github.com/hgrecco/pint/issues/85", "id": 25334075, "node_id": "MDU6SXNzdWUyNTMzNDA3NQ==", "number": 85, "title": "problem with constants (boltzmann_constant)", "user": {"login": "exxus", "id": 6360942, "node_id": "MDQ6VXNlcjYzNjA5NDI=", "avatar_url": "https://avatars.githubusercontent.com/u/6360942?v=4", "gravatar_id": "", "url": "https://api.github.com/users/exxus", "html_url": "https://github.com/exxus", "followers_url": "https://api.github.com/users/exxus/followers", "following_url": "https://api.github.com/users/exxus/following{/other_user}", "gists_url": "https://api.github.com/users/exxus/gists{/gist_id}", "starred_url": "https://api.github.com/users/exxus/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/exxus/subscriptions", "organizations_url": "https://api.github.com/users/exxus/orgs", "repos_url": "https://api.github.com/users/exxus/repos", "events_url": "https://api.github.com/users/exxus/events{/privacy}", "received_events_url": "https://api.github.com/users/exxus/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2014-01-09T16:59:43Z", "updated_at": "2014-01-14T02:25:23Z", "closed_at": "2014-01-10T12:49:49Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\nI recently started using this library and I really like it. I am new to python, but nevertheless I hope my comments will help a little.\nToday I found a problem when working with predefined constants.\nHere my example (calculating the velocity of a particle):\n\n``` python\nimport numpy as np\nfrom pint import UnitRegistry\nureg=UnitRegistry()\n\nT=473*ureg.degK\nm=132.9054519*ureg.amu\nva=np.sqrt(2*ureg.k*T/m)\n\nprint(va)\n2.6679283991697362 boltzmann_constant ** 0.5 * degK ** 0.5 / atomic_mass_unit ** 0.5\n```\n\nOf course I want to convert it to a convenient unit, but this results in an error that I don't really understand:\n\n``` python\nva.to_base_units()\n---------------------------------------------------------------------------\nTypeError                                 Traceback (most recent call last)\n<ipython-input-7-ea6209013126> in <module>()\n----> 1 va.to_base_units()\n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/quantity.py in to_base_units(self)\n    251 \n    252         ret = copy.copy(self)\n--> 253         ret.ito_base_units()\n    254         return ret\n    255 \n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/quantity.py in ito_base_units(self)\n    242         _, other = self._REGISTRY.get_base_units(self.units)\n    243 \n--> 244         self._magnitude = self._convert_magnitude(other)\n    245         self._units = other\n    246         return self\n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/quantity.py in _convert_magnitude(self, other, *contexts, **ctx_kwargs)\n    205                 return self._REGISTRY.convert(self._magnitude, self._units, other)\n    206 \n--> 207         return self._REGISTRY.convert(self._magnitude, self._units, other)\n    208 \n    209     def ito(self, other=None, *contexts, **ctx_kwargs):\n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/unit.py in convert(self, value, src, dst)\n    877             return Decimal(str(factor)) * value\n    878 \n--> 879         return factor * value\n    880 \n    881     def pi_theorem(self, quantities):\n\nTypeError: unsupported operand type(s) for *: 'NoneType' and 'float'\n```\n\nThe same for\n\n``` python\nva.to(ureg.m/ureg.s)\n```\n\nMy workaround was defining the Boltzmann constant by myself\n\n``` python\nboltmk=1.3806488e-23*ureg.J/ureg.K\nvb=np.sqrt(2*boltmk*T/m)\nvb.to_base_units()\n243.2715198052687 meter/second\n```\n\nAs far as I understand, the constants are just units themselves.\nBut defining my own Boltzmann constant unit raised also an error:\n\n``` python\nureg.define('boltzmk = 1.3806488e-23 joule / degK')\nureg.boltzmk.to_base_units()\n---------------------------------------------------------------------------\nTypeError                                 Traceback (most recent call last)\n<ipython-input-26-c1e1448209d2> in <module>()\n----> 1 ureg.boltzmk.to_base_units()\n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/quantity.py in to_base_units(self)\n    251 \n    252         ret = copy.copy(self)\n--> 253         ret.ito_base_units()\n    254         return ret\n    255 \n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/quantity.py in ito_base_units(self)\n    240         \"\"\"\n    241 \n--> 242         _, other = self._REGISTRY.get_base_units(self.units)\n    243 \n    244         self._magnitude = self._convert_magnitude(other)\n\n/usr/lib/python3.3/site-packages/Pint-0.4-py3.3.egg/pint/unit.py in get_base_units(self, input_units)\n    812                 fac, uni = self.get_base_units(reg.reference)\n    813                 if factor is not None:\n--> 814                     factor *= (reg.converter.scale * fac) ** value\n    815                 units *= uni ** value\n    816 \n\nTypeError: unsupported operand type(s) for *: 'float' and 'NoneType'\n```\n\nWhile reading the files for unit definiton (default_en.txt) and (constants_en.txt) I also saw that the symbol h is used for hour and for Planck constant.\nI don't know if this was intended.\n\nI am using pint 0.4 with python 3.3.3-1.\n\nThank You,\nexxus\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/85/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/85/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/82", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/82/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/82/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/82/events", "html_url": "https://github.com/hgrecco/pint/issues/82", "id": 24839883, "node_id": "MDU6SXNzdWUyNDgzOTg4Mw==", "number": 82, "title": "Name conflict between hour and Planck's constant", "user": {"login": "choloepus", "id": 6274016, "node_id": "MDQ6VXNlcjYyNzQwMTY=", "avatar_url": "https://avatars.githubusercontent.com/u/6274016?v=4", "gravatar_id": "", "url": "https://api.github.com/users/choloepus", "html_url": "https://github.com/choloepus", "followers_url": "https://api.github.com/users/choloepus/followers", "following_url": "https://api.github.com/users/choloepus/following{/other_user}", "gists_url": "https://api.github.com/users/choloepus/gists{/gist_id}", "starred_url": "https://api.github.com/users/choloepus/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/choloepus/subscriptions", "organizations_url": "https://api.github.com/users/choloepus/orgs", "repos_url": "https://api.github.com/users/choloepus/repos", "events_url": "https://api.github.com/users/choloepus/events{/privacy}", "received_events_url": "https://api.github.com/users/choloepus/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-12-28T02:19:01Z", "updated_at": "2014-01-10T01:29:31Z", "closed_at": "2013-12-29T15:02:37Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "constants_en.txt defines \"h\" as Planck's constant, but default_en.txt defines \"h\" as hour. The result is that ureg.h ends up as the hour.\n\nI would recommend removing \"h\" from default_en.txt, since \"hr\" and \"hour\" are pretty good names for the hour, but \"planck_constant\" is rather unwieldy and there is no other widely used abbreviation.\n\nThis line of default_en.txt is also used as an example in the documentation on the \"Defining units\" page, so it should be changed there as well if default_en.txt is changed.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/82/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/82/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/80", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/80/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/80/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/80/events", "html_url": "https://github.com/hgrecco/pint/issues/80", "id": 24732400, "node_id": "MDU6SXNzdWUyNDczMjQwMA==", "number": 80, "title": "Integer Division with Arrays", "user": {"login": "jdreaver", "id": 1253071, "node_id": "MDQ6VXNlcjEyNTMwNzE=", "avatar_url": "https://avatars.githubusercontent.com/u/1253071?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jdreaver", "html_url": "https://github.com/jdreaver", "followers_url": "https://api.github.com/users/jdreaver/followers", "following_url": "https://api.github.com/users/jdreaver/following{/other_user}", "gists_url": "https://api.github.com/users/jdreaver/gists{/gist_id}", "starred_url": "https://api.github.com/users/jdreaver/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jdreaver/subscriptions", "organizations_url": "https://api.github.com/users/jdreaver/orgs", "repos_url": "https://api.github.com/users/jdreaver/repos", "events_url": "https://api.github.com/users/jdreaver/events{/privacy}", "received_events_url": "https://api.github.com/users/jdreaver/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2013-12-24T02:16:04Z", "updated_at": "2013-12-26T15:21:37Z", "closed_at": "2013-12-26T15:21:37Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I am currently using Python 3.3 and Pint 0.4. When integer arrays are used in quantities, division is truncated integer division instead of floating point. For example:\n\n``` python\n>>> a = np.array([1]) * ureg['m']\n\n>>> b = np.array([2]) * ureg['s']\n\n>>> a/b\n<Quantity([0], 'meter / second')>\n\n>>> a.magnitude / b.magnitude  # Numpy division\narray([ 0.5])  # Correct\n\n>>> ureg['1 m'] / ureg['2 s']  # Not using arrays\n<Quantity(0.5, 'meter / second')>\n```\n\nIs this a bug? I am assuming the intended behavior is to use floating point division where appropriate like Python 3, instead of integer division.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/80/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/80/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/68", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/68/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/68/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/68/events", "html_url": "https://github.com/hgrecco/pint/issues/68", "id": 20541692, "node_id": "MDU6SXNzdWUyMDU0MTY5Mg==", "number": 68, "title": "Issue with no constants_en.txt unpacked (Python3.3 Windows 7)", "user": {"login": "DuaneKaufman", "id": 5613504, "node_id": "MDQ6VXNlcjU2MTM1MDQ=", "avatar_url": "https://avatars.githubusercontent.com/u/5613504?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DuaneKaufman", "html_url": "https://github.com/DuaneKaufman", "followers_url": "https://api.github.com/users/DuaneKaufman/followers", "following_url": "https://api.github.com/users/DuaneKaufman/following{/other_user}", "gists_url": "https://api.github.com/users/DuaneKaufman/gists{/gist_id}", "starred_url": "https://api.github.com/users/DuaneKaufman/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DuaneKaufman/subscriptions", "organizations_url": "https://api.github.com/users/DuaneKaufman/orgs", "repos_url": "https://api.github.com/users/DuaneKaufman/repos", "events_url": "https://api.github.com/users/DuaneKaufman/events{/privacy}", "received_events_url": "https://api.github.com/users/DuaneKaufman/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 16, "created_at": "2013-10-04T18:22:22Z", "updated_at": "2013-10-22T05:16:04Z", "closed_at": "2013-10-22T03:11:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\nAfter installing pint on a Windows 7 machine, I get an error on import:\n\nPython 3.3.2 (v3.3.2:d047928ae3f6, May 16 2013, 00:03:43) [MSC v.1600 32 bit (In\ntel)] on win32\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\n> > > import pint\n> > > Traceback (most recent call last):\n> > >   File \"<stdin>\", line 1, in <module>\n> > >   File \"<frozen importlib._bootstrap>\", line 1567, in _find_and_load\n> > >   File \"<frozen importlib._bootstrap>\", line 1534, in _find_and_load_unlocked\n> > >   File \"c:\\python33\\lib\\site-packages\\pint-0.4.dev0-py3.3.egg\\pint__init__.py\",\n> > >  line 22, in <module>\n> > >   File \"c:\\python33\\lib\\site-packages\\pint-0.4.dev0-py3.3.egg\\pint\\unit.py\", lin\n> > > e 417, in **init**\n> > >   File \"c:\\python33\\lib\\site-packages\\pint-0.4.dev0-py3.3.egg\\pint\\unit.py\", lin\n> > > e 492, in load_definitions\n> > >   File \"c:\\python33\\lib\\site-packages\\pint-0.4.dev0-py3.3.egg\\pint\\unit.py\", lin\n> > > e 504, in load_definitions\n> > >   File \"c:\\python33\\lib\\site-packages\\pint-0.4.dev0-py3.3.egg\\pint\\unit.py\", lin\n> > > e 491, in load_definitions\n> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dkaufman\\Ap\n> > > pData\\Roaming\\Python-Eggs\\pint-0.4.dev0-py3.3.egg-tmp\\pint\\constants_en.txt\n> > > '\n> > > For some reason, it seems that upon import, defaults_en.txt gets unpacked, but not constants_en.txt\n\nThanks,\nDuane\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/68/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/68/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/66", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/66/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/66/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/66/events", "html_url": "https://github.com/hgrecco/pint/issues/66", "id": 19756737, "node_id": "MDU6SXNzdWUxOTc1NjczNw==", "number": 66, "title": "get_dimensionality is broken for non multiplicative units", "user": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-09-19T14:09:41Z", "updated_at": "2013-10-06T23:59:15Z", "closed_at": "2013-10-06T23:59:15Z", "author_association": "OWNER", "active_lock_reason": null, "body": "", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/66/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/66/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/62", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/62/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/62/events", "html_url": "https://github.com/hgrecco/pint/issues/62", "id": 19401351, "node_id": "MDU6SXNzdWUxOTQwMTM1MQ==", "number": 62, "title": "Printing Fractional Exponents Less than 1", "user": {"login": "jdreaver", "id": 1253071, "node_id": "MDQ6VXNlcjEyNTMwNzE=", "avatar_url": "https://avatars.githubusercontent.com/u/1253071?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jdreaver", "html_url": "https://github.com/jdreaver", "followers_url": "https://api.github.com/users/jdreaver/followers", "following_url": "https://api.github.com/users/jdreaver/following{/other_user}", "gists_url": "https://api.github.com/users/jdreaver/gists{/gist_id}", "starred_url": "https://api.github.com/users/jdreaver/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jdreaver/subscriptions", "organizations_url": "https://api.github.com/users/jdreaver/orgs", "repos_url": "https://api.github.com/users/jdreaver/repos", "events_url": "https://api.github.com/users/jdreaver/events{/privacy}", "received_events_url": "https://api.github.com/users/jdreaver/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-09-12T17:19:23Z", "updated_at": "2013-09-12T23:01:29Z", "closed_at": "2013-09-12T23:01:29Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Whenever you create a unit with a fractional exponent less than one, it is printed as if the exponent is negative. However, the internal representation of the units is still correct. Consider the following examples:\n\n``` python\n>>> ureg['m^0.5']                      # 0.5 < 1\n<Quantity(1.0, '1 / meter ** 0.5')>    # The printing indicates m^-0.5\n>>> ureg['m^0.5'].units\n<UnitsContainer({'meter': 0.5})>       # But the internal representation is fine\n\n>>> ureg['m^-0.5']\n<Quantity(1.0, '1 / meter ** 0.5')>    # Notice the same printing as above\n>>> ureg['m^-0.5'].units\n<UnitsContainer({'meter': -0.5})>\n\n>>> ureg['m^0.5'] * ureg['m^-0.5']\n<Quantity(1.0, 'dimensionless')>       # This is still correct\n\n>>> ureg['m^1.1']\n<Quantity(1.0, 'meter ** 1.1')>        # 1.1 > 1, correct printing\n>>> ureg['m^0.9']\n<Quantity(1.0, '1 / meter ** 0.9')>    # 0.9 < 1, printing as if -0.9\n```\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/62/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/62/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/61", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/61/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/61/events", "html_url": "https://github.com/hgrecco/pint/issues/61", "id": 19361565, "node_id": "MDU6SXNzdWUxOTM2MTU2NQ==", "number": 61, "title": "The package is no longer zip_safe due to the implementation of @import", "user": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-09-12T04:34:03Z", "updated_at": "2013-09-15T00:41:36Z", "closed_at": "2013-09-15T00:41:36Z", "author_association": "OWNER", "active_lock_reason": null, "body": "", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/61/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/61/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/54", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/54/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/54/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/54/events", "html_url": "https://github.com/hgrecco/pint/issues/54", "id": 18621769, "node_id": "MDU6SXNzdWUxODYyMTc2OQ==", "number": 54, "title": "Dimensionless Quantities behave unexpectedly when added to 'raw' numbers", "user": {"login": "natezb", "id": 3268059, "node_id": "MDQ6VXNlcjMyNjgwNTk=", "avatar_url": "https://avatars.githubusercontent.com/u/3268059?v=4", "gravatar_id": "", "url": "https://api.github.com/users/natezb", "html_url": "https://github.com/natezb", "followers_url": "https://api.github.com/users/natezb/followers", "following_url": "https://api.github.com/users/natezb/following{/other_user}", "gists_url": "https://api.github.com/users/natezb/gists{/gist_id}", "starred_url": "https://api.github.com/users/natezb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/natezb/subscriptions", "organizations_url": "https://api.github.com/users/natezb/orgs", "repos_url": "https://api.github.com/users/natezb/repos", "events_url": "https://api.github.com/users/natezb/events{/privacy}", "received_events_url": "https://api.github.com/users/natezb/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-08-27T17:30:58Z", "updated_at": "2014-07-09T18:57:05Z", "closed_at": "2013-08-28T03:34:26Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "This issue is similar to issue #45 (thanks for fixing that, btw).\n\nWhen dimensionless Quantities are added to 'raw' number types (int, float, np.float64, etc.), the number seems to be added directly to the magnitude of the Quantity rather than being properly converted to the Quantity's special 'unitless' units. For example:\n\n```\n>>> (ureg.km/ureg.m + 1).to('')\n<Quantity(2000.0, 'dimensionless')>    # Wrong\n>>> (ureg.km/ureg.m).to('') + 1\n<Quantity(1001.0, 'dimensionless')>    # Correct\n```\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/54/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/54/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/50", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/50/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/50/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/50/events", "html_url": "https://github.com/hgrecco/pint/issues/50", "id": 18244862, "node_id": "MDU6SXNzdWUxODI0NDg2Mg==", "number": 50, "title": "AttributeError: 'int' object has no attribute '_Quantity__handling'", "user": {"login": "danielsokolowski", "id": 273413, "node_id": "MDQ6VXNlcjI3MzQxMw==", "avatar_url": "https://avatars.githubusercontent.com/u/273413?v=4", "gravatar_id": "", "url": "https://api.github.com/users/danielsokolowski", "html_url": "https://github.com/danielsokolowski", "followers_url": "https://api.github.com/users/danielsokolowski/followers", "following_url": "https://api.github.com/users/danielsokolowski/following{/other_user}", "gists_url": "https://api.github.com/users/danielsokolowski/gists{/gist_id}", "starred_url": "https://api.github.com/users/danielsokolowski/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/danielsokolowski/subscriptions", "organizations_url": "https://api.github.com/users/danielsokolowski/orgs", "repos_url": "https://api.github.com/users/danielsokolowski/repos", "events_url": "https://api.github.com/users/danielsokolowski/events{/privacy}", "received_events_url": "https://api.github.com/users/danielsokolowski/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-08-19T15:11:19Z", "updated_at": "2013-08-20T03:18:31Z", "closed_at": "2013-08-20T03:18:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "Expected result below ought to be '100 dimensionless'. \n\n```\nself.unitregistry.Quantity(100)\n100 dimensionless\nself.unitregistry.Quantity('100')\nTraceback (most recent call last):\n  File \"/srv/www/django/development.<hidden>/src/github-texer-pydevsrc/pydevsrc/pydevd_comm.py\", line 752, in doIt\n    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)\n  File \"/srv/www/django/development.<hidden>/src/github-texer-pydevsrc/pydevsrc/pydevd_vars.py\", line 375, in evaluateExpression\n    result = eval(compiled, updated_globals, frame.f_locals)\n  File \"<string>\", line 1, in <module>\n  File \"/srv/www/django/development.<hidden>/src/github-danielsokolowski-django-unitofmeasure/unitofmeasure/danielsokolowski-pint/pint/quantity.py\", line 96, in __new__\n    inst.__handling = None\nAttributeError: 'int' object has no attribute '_Quantity__handling'\nself.unitregistry.Quantity(100.00)\n100.0 dimensionless\nself.unitregistry.Quantity(Decimal('100'))\n100 dimensionless\n```\n\nPerhaps consider putting 'beta' status back onto the package, this is not production ready. \n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/50/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/50/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/45", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/45/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/45/events", "html_url": "https://github.com/hgrecco/pint/issues/45", "id": 18130860, "node_id": "MDU6SXNzdWUxODEzMDg2MA==", "number": 45, "title": "Dimensionless Quantities behave unexpectedly with some math functions", "user": {"login": "natezb", "id": 3268059, "node_id": "MDQ6VXNlcjMyNjgwNTk=", "avatar_url": "https://avatars.githubusercontent.com/u/3268059?v=4", "gravatar_id": "", "url": "https://api.github.com/users/natezb", "html_url": "https://github.com/natezb", "followers_url": "https://api.github.com/users/natezb/followers", "following_url": "https://api.github.com/users/natezb/following{/other_user}", "gists_url": "https://api.github.com/users/natezb/gists{/gist_id}", "starred_url": "https://api.github.com/users/natezb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/natezb/subscriptions", "organizations_url": "https://api.github.com/users/natezb/orgs", "repos_url": "https://api.github.com/users/natezb/repos", "events_url": "https://api.github.com/users/natezb/events{/privacy}", "received_events_url": "https://api.github.com/users/natezb/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-08-15T21:59:43Z", "updated_at": "2013-08-27T17:30:58Z", "closed_at": "2013-08-20T03:10:47Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "This behavior applies to both numpy and python standard mathematical functions. Firstly, np.sqrt behaves as expected (provided you work around issue #44 ), while math.sqrt first exhibits the issue:\n\n```\n>>> np.sqrt( [1] * ureg.m/ureg.cm )\n<Quantity([ 1.], '1 / centimeter ** 0.5 / meter ** 0.5')>\n>>> _.to('')\n<Quantity([ 10.], 'dimensionless')>\n>>> math.sqrt( 1 * ureg.m/ureg.cm )\n1.0\n```\n\nIn the first case, units are retained, so the dimensionless quantity stays correct. However, in the second case I believe the quantity is cast to a float by directly taking the magnitude, which is 1.0 (in units of m/cm) rather than (the truly dimensionless) 100, which is expected.\n\nWhen casting a dimensionless Quantity to a float, the most sensible float value is the value of the 'true' dimensionless number. Otherwise you get extremely unintuitive results such as\n\n```\n>>> float(ureg.V/ureg.mV)\n1.0\n```\n\nFurthermore, this requires an ugly and cumbersome workaround to work as expected. \n\n```\n>>> float( (ureg.V/ureg.mV).to('') )\n1000.0\n```\n\nSimply not using python's math module isn't a solution, since similar issues can be found with when using numpy as in `np.sin()`:\n\n```\n>>> np.sin( [np.pi/2] * ureg.m/ureg.m )\n<Quantity([ 1.], 'dimensionless')>\n>>> np.sin( [np.pi/2] * ureg.cm/ureg.m )\n<Quantity([ 1.], 'dimensionless')>\n>>> np.sin( ([np.pi/2] * ureg.cm/ureg.m).to('') )\n<Quantity([ 0.01570732], 'dimensionless')>\n```\n\nInterestingly, `np.arccos()` seems to work as expected:\n\n```\n>>> np.arccos( [1] * ureg.m/ureg.m )\n<Quantity([ 0.], 'radian')>\n>>> np.arccos( [1] * ureg.cm/ureg.m )\n<Quantity([ 1.56079616], 'radian')>\n```\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/45/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/45/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/44", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/44/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/44/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/44/events", "html_url": "https://github.com/hgrecco/pint/issues/44", "id": 18128668, "node_id": "MDU6SXNzdWUxODEyODY2OA==", "number": 44, "title": "Single-number Quantities don't work with ufuncs", "user": {"login": "natezb", "id": 3268059, "node_id": "MDQ6VXNlcjMyNjgwNTk=", "avatar_url": "https://avatars.githubusercontent.com/u/3268059?v=4", "gravatar_id": "", "url": "https://api.github.com/users/natezb", "html_url": "https://github.com/natezb", "followers_url": "https://api.github.com/users/natezb/followers", "following_url": "https://api.github.com/users/natezb/following{/other_user}", "gists_url": "https://api.github.com/users/natezb/gists{/gist_id}", "starred_url": "https://api.github.com/users/natezb/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/natezb/subscriptions", "organizations_url": "https://api.github.com/users/natezb/orgs", "repos_url": "https://api.github.com/users/natezb/repos", "events_url": "https://api.github.com/users/natezb/events{/privacy}", "received_events_url": "https://api.github.com/users/natezb/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2013-08-15T21:16:19Z", "updated_at": "2013-08-20T03:10:47Z", "closed_at": "2013-08-20T03:10:47Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Quantity objects that contain a single number (as opposed to an array) are not compatible with numpy ufuncs. For example:\n\n```\n>>> np.sqrt( ureg.dimensionless )\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nAttributeError: sqrt\n>>> np.sqrt( [1] * ureg.dimensionless )\n<Quantity([ 1.], 'dimensionless')>\n```\n\nThis is in contrast to numpy itself whose ufuncs can apply to a single value:\n\n```\n>>> np.sqrt(4)\n2.0\n```\n\nThis makes using unit-ful single-value variables more cumbersome than it should be.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/44/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/44/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/41", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/41/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/41/events", "html_url": "https://github.com/hgrecco/pint/issues/41", "id": 18078500, "node_id": "MDU6SXNzdWUxODA3ODUwMA==", "number": 41, "title": "Conversion from bar to mbar failed [Bug]", "user": {"login": "Bachibouzouk", "id": 4399407, "node_id": "MDQ6VXNlcjQzOTk0MDc=", "avatar_url": "https://avatars.githubusercontent.com/u/4399407?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Bachibouzouk", "html_url": "https://github.com/Bachibouzouk", "followers_url": "https://api.github.com/users/Bachibouzouk/followers", "following_url": "https://api.github.com/users/Bachibouzouk/following{/other_user}", "gists_url": "https://api.github.com/users/Bachibouzouk/gists{/gist_id}", "starred_url": "https://api.github.com/users/Bachibouzouk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Bachibouzouk/subscriptions", "organizations_url": "https://api.github.com/users/Bachibouzouk/orgs", "repos_url": "https://api.github.com/users/Bachibouzouk/repos", "events_url": "https://api.github.com/users/Bachibouzouk/events{/privacy}", "received_events_url": "https://api.github.com/users/Bachibouzouk/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-08-14T21:35:36Z", "updated_at": "2013-08-14T23:18:04Z", "closed_at": "2013-08-14T23:17:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\n\nI noticed an issue with the unit bar for the pressure, it seems that the parser which detects the prefixex such as m- for milli- does not work in that case.\n\nHere is an example I ran and the error code\n\nCheers\n\nBachibouzouk\n\nPython 2.7.3 (default, Jul  5 2013, 08:52:38) \n[GCC 4.6.3] on linux2\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\nImported NumPy 1.6.1, SciPy 0.9.0, Matplotlib 1.1.1rc \nType \"scientific\" for more details.\n\n> > > from pint import UnitRegistry\n> > > ureg=UnitRegistry()\n> > > P=ureg.bar\n> > > P.to('Pa')\n> > > <Quantity(100000.0, 'pascal')>\n> > > P.to('mPa')\n> > > <Quantity(100000000.0, 'millipascal')>\n> > > P.to('mbar')\n> > > Traceback (most recent call last):\n> > >   File \"<stdin>\", line 1, in <module>\n> > >   File \"/usr/local/lib/python2.7/dist-packages/Pint-0.3.dev0-py2.7.egg/pint/quantity.py\", line 192, in to\n> > >     ret.ito(other)\n> > >   File \"/usr/local/lib/python2.7/dist-packages/Pint-0.3.dev0-py2.7.egg/pint/quantity.py\", line 175, in ito\n> > >     other = self._REGISTRY.parse_units(other)\n> > >   File \"/usr/local/lib/python2.7/dist-packages/Pint-0.3.dev0-py2.7.egg/pint/unit.py\", line 746, in parse_units\n> > >     cname = self.get_name(name)\n> > >   File \"/usr/local/lib/python2.7/dist-packages/Pint-0.3.dev0-py2.7.egg/pint/unit.py\", line 549, in get_name\n> > >     symbol = self.get_symbol(name)\n> > >   File \"/usr/local/lib/python2.7/dist-packages/Pint-0.3.dev0-py2.7.egg/pint/unit.py\", line 570, in get_symbol\n> > >     return self._prefixes[prefix].symbol + self._units[unit_name].symbol\n> > > TypeError: coercing to Unicode: need string or buffer, NoneType found\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/41/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/41/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/37", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/37/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/37/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/37/events", "html_url": "https://github.com/hgrecco/pint/issues/37", "id": 17168374, "node_id": "MDU6SXNzdWUxNzE2ODM3NA==", "number": 37, "title": "Operating elementwise with numpy masked arrays", "user": {"login": "canesin", "id": 353648, "node_id": "MDQ6VXNlcjM1MzY0OA==", "avatar_url": "https://avatars.githubusercontent.com/u/353648?v=4", "gravatar_id": "", "url": "https://api.github.com/users/canesin", "html_url": "https://github.com/canesin", "followers_url": "https://api.github.com/users/canesin/followers", "following_url": "https://api.github.com/users/canesin/following{/other_user}", "gists_url": "https://api.github.com/users/canesin/gists{/gist_id}", "starred_url": "https://api.github.com/users/canesin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/canesin/subscriptions", "organizations_url": "https://api.github.com/users/canesin/orgs", "repos_url": "https://api.github.com/users/canesin/repos", "events_url": "https://api.github.com/users/canesin/events{/privacy}", "received_events_url": "https://api.github.com/users/canesin/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}, {"id": 9211127, "node_id": "MDU6TGFiZWw5MjExMTI3", "url": "https://api.github.com/repos/hgrecco/pint/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}, {"id": 1712992969, "node_id": "MDU6TGFiZWwxNzEyOTkyOTY5", "url": "https://api.github.com/repos/hgrecco/pint/labels/numpy", "name": "numpy", "color": "e8a4e6", "default": false, "description": "Numpy related bug/enhancement"}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2013-07-24T16:59:31Z", "updated_at": "2019-12-30T16:45:25Z", "closed_at": "2019-12-30T16:45:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "It is not working as suposed with masked arrays, it creats objects by elements.\n\nhttps://gist.github.com/canesin/6072390\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/37/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/37/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/35", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/35/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/35/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/35/events", "html_url": "https://github.com/hgrecco/pint/issues/35", "id": 17075896, "node_id": "MDU6SXNzdWUxNzA3NTg5Ng==", "number": 35, "title": "Comparison of UnitsContainer to string", "user": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": {"url": "https://api.github.com/repos/hgrecco/pint/milestones/2", "html_url": "https://github.com/hgrecco/pint/milestone/2", "labels_url": "https://api.github.com/repos/hgrecco/pint/milestones/2/labels", "id": 323397, "node_id": "MDk6TWlsZXN0b25lMzIzMzk3", "number": 2, "title": "0.3", "description": null, "creator": {"login": "hgrecco", "id": 278566, "node_id": "MDQ6VXNlcjI3ODU2Ng==", "avatar_url": "https://avatars.githubusercontent.com/u/278566?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hgrecco", "html_url": "https://github.com/hgrecco", "followers_url": "https://api.github.com/users/hgrecco/followers", "following_url": "https://api.github.com/users/hgrecco/following{/other_user}", "gists_url": "https://api.github.com/users/hgrecco/gists{/gist_id}", "starred_url": "https://api.github.com/users/hgrecco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hgrecco/subscriptions", "organizations_url": "https://api.github.com/users/hgrecco/orgs", "repos_url": "https://api.github.com/users/hgrecco/repos", "events_url": "https://api.github.com/users/hgrecco/events{/privacy}", "received_events_url": "https://api.github.com/users/hgrecco/received_events", "type": "User", "site_admin": false}, "open_issues": 0, "closed_issues": 6, "state": "closed", "created_at": "2013-04-29T19:13:43Z", "updated_at": "2019-12-03T17:34:22Z", "due_on": null, "closed_at": "2014-10-30T19:54:52Z"}, "comments": 0, "created_at": "2013-07-22T23:08:30Z", "updated_at": "2013-08-14T23:17:45Z", "closed_at": "2013-08-14T23:17:45Z", "author_association": "OWNER", "active_lock_reason": null, "body": "Implements \n\n```\n>>> ureg.Quantity(1, 'meter').units == 'meter'\nTrue\n```\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/35/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/35/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/29", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/29/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/29/events", "html_url": "https://github.com/hgrecco/pint/issues/29", "id": 14648648, "node_id": "MDU6SXNzdWUxNDY0ODY0OA==", "number": 29, "title": "Special casing 1 dimension in unit.convert() leads to confusing error", "user": {"login": "MrCreosote", "id": 1686141, "node_id": "MDQ6VXNlcjE2ODYxNDE=", "avatar_url": "https://avatars.githubusercontent.com/u/1686141?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MrCreosote", "html_url": "https://github.com/MrCreosote", "followers_url": "https://api.github.com/users/MrCreosote/followers", "following_url": "https://api.github.com/users/MrCreosote/following{/other_user}", "gists_url": "https://api.github.com/users/MrCreosote/gists{/gist_id}", "starred_url": "https://api.github.com/users/MrCreosote/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MrCreosote/subscriptions", "organizations_url": "https://api.github.com/users/MrCreosote/orgs", "repos_url": "https://api.github.com/users/MrCreosote/repos", "events_url": "https://api.github.com/users/MrCreosote/events{/privacy}", "received_events_url": "https://api.github.com/users/MrCreosote/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-05-22T22:18:19Z", "updated_at": "2013-05-23T11:29:21Z", "closed_at": "2013-05-23T03:37:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "Firstly, pint is really great. I've been looking for a good units package for months - finally stumbled across pint and it's just what I was hoping for. \n\nNot sure if this is a bug or an enhancement, but the special casing in line 637 of unit.convert() leads to very confusing error messages when performing valid unit conversions where the source units which are defined as a function of multiple units:\n\n```\nIn [1]: import pint\n\nIn [2]: pint.__version__\nOut[2]: '0.2'\n\nIn [3]: ureg = pint.UnitRegistry()\n\nIn [4]: ureg.define('molar = mole / liter = M')\n\nIn [5]: t = 4 * ureg['mM']\n\nIn [6]: t\nOut[6]: <Quantity(4, 'millimolar')>\n\nIn [7]: t.to('mole / liter')\n\nDimensionalityError                       Traceback (most recent call last)\n<ipython-input-7-5efb6e276de9> in <module>()\n----> 1 t.to('mole / liter')\n\n/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in to(self, other)\n    189         \"\"\"\n    190         ret = copy.copy(self)\n--> 191         ret.ito(other)\n    192         return ret\n    193 \n\n/usr/local/lib/python2.7/dist-packages/pint/quantity.pyc in ito(self, other)\n    178             other = UnitsContainer(other)\n    179 \n--> 180         self._magnitude = self._REGISTRY.convert(self._magnitude, self._units, other)\n    181         self._units = other\n    182         return self\n\n/usr/local/lib/python2.7/dist-packages/pint/unit.py in convert(self, value, src, dst)\n    639                 raise DimensionalityError(src, dst,\n    640                                           self.get_dimensionality(src),\n--> 641                                           self.get_dimensionality(dst))\n    642             src_unit, src_value = list(src.items())[0]\n    643             src_unit = self._units[src_unit]\n\nDimensionalityError: Cannot convert from 'millimolar' ([substance] / [length] ** 3) to \n'mole / liter'  ([substance] / [length] ** 3)\n```\n\nI'd naively expect that to work correctly. The workaround is to convert to molar rather than mol/L.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/29/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/29/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/25", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/25/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/25/events", "html_url": "https://github.com/hgrecco/pint/issues/25", "id": 14375671, "node_id": "MDU6SXNzdWUxNDM3NTY3MQ==", "number": 25, "title": "Unicode support", "user": {"login": "mrijken", "id": 1752360, "node_id": "MDQ6VXNlcjE3NTIzNjA=", "avatar_url": "https://avatars.githubusercontent.com/u/1752360?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mrijken", "html_url": "https://github.com/mrijken", "followers_url": "https://api.github.com/users/mrijken/followers", "following_url": "https://api.github.com/users/mrijken/following{/other_user}", "gists_url": "https://api.github.com/users/mrijken/gists{/gist_id}", "starred_url": "https://api.github.com/users/mrijken/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mrijken/subscriptions", "organizations_url": "https://api.github.com/users/mrijken/orgs", "repos_url": "https://api.github.com/users/mrijken/repos", "events_url": "https://api.github.com/users/mrijken/events{/privacy}", "received_events_url": "https://api.github.com/users/mrijken/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-05-15T19:46:39Z", "updated_at": "2015-01-26T11:10:24Z", "closed_at": "2015-01-26T11:10:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have added percent and permille to my definitions via:\n\n```\npercent = [fraction]; offset: 0 = %\npermille = percent / 10 = \u2030\n```\n\nThose definitions are loaded without any errors.\n\nWhen I parse percents like 100 %, this works as expected. However with 100 \u2030, I get the following error:\n\n```\n  File \"/var/atmiz/eggs/Pint-0.2-py2.7.egg/pint/quantity.py\", line 88, in __new__\n    inst._units = inst._REGISTRY.parse_units(units)\n  File \"/var/atmiz/eggs/Pint-0.2-py2.7.egg/pint/unit.py\", line 723, in parse_units\n    units = ParserHelper.from_string(input_string)\n  File \"/var/atmiz/eggs/Pint-0.2-py2.7.egg/pint/util.py\", line 320, in from_string\n    {'L_': cls})\n  File \"<string>\", line 1\n    \u00e2\u0080\u00b0\n    ^\nSyntaxError: invalid syntax\n```\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/25/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/25/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/4", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/4/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/4/events", "html_url": "https://github.com/hgrecco/pint/issues/4", "id": 9659322, "node_id": "MDU6SXNzdWU5NjU5MzIy", "number": 4, "title": "Watt-hour is defined incorrectly", "user": {"login": "craigholm", "id": 1476786, "node_id": "MDQ6VXNlcjE0NzY3ODY=", "avatar_url": "https://avatars.githubusercontent.com/u/1476786?v=4", "gravatar_id": "", "url": "https://api.github.com/users/craigholm", "html_url": "https://github.com/craigholm", "followers_url": "https://api.github.com/users/craigholm/followers", "following_url": "https://api.github.com/users/craigholm/following{/other_user}", "gists_url": "https://api.github.com/users/craigholm/gists{/gist_id}", "starred_url": "https://api.github.com/users/craigholm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/craigholm/subscriptions", "organizations_url": "https://api.github.com/users/craigholm/orgs", "repos_url": "https://api.github.com/users/craigholm/repos", "events_url": "https://api.github.com/users/craigholm/events{/privacy}", "received_events_url": "https://api.github.com/users/craigholm/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-01-03T23:03:50Z", "updated_at": "2013-01-04T10:56:30Z", "closed_at": "2013-01-04T10:56:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "In default_en.txt, watt-hour is defined as watt / hour.  It should be watt \\* hour.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/4/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/4/timeline", "performed_via_github_app": null, "state_reason": "completed"}, {"url": "https://api.github.com/repos/hgrecco/pint/issues/3", "repository_url": "https://api.github.com/repos/hgrecco/pint", "labels_url": "https://api.github.com/repos/hgrecco/pint/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/hgrecco/pint/issues/3/comments", "events_url": "https://api.github.com/repos/hgrecco/pint/issues/3/events", "html_url": "https://github.com/hgrecco/pint/issues/3", "id": 9659265, "node_id": "MDU6SXNzdWU5NjU5MjY1", "number": 3, "title": "Temperature conversions are incorrect", "user": {"login": "craigholm", "id": 1476786, "node_id": "MDQ6VXNlcjE0NzY3ODY=", "avatar_url": "https://avatars.githubusercontent.com/u/1476786?v=4", "gravatar_id": "", "url": "https://api.github.com/users/craigholm", "html_url": "https://github.com/craigholm", "followers_url": "https://api.github.com/users/craigholm/followers", "following_url": "https://api.github.com/users/craigholm/following{/other_user}", "gists_url": "https://api.github.com/users/craigholm/gists{/gist_id}", "starred_url": "https://api.github.com/users/craigholm/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/craigholm/subscriptions", "organizations_url": "https://api.github.com/users/craigholm/orgs", "repos_url": "https://api.github.com/users/craigholm/repos", "events_url": "https://api.github.com/users/craigholm/events{/privacy}", "received_events_url": "https://api.github.com/users/craigholm/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 9211125, "node_id": "MDU6TGFiZWw5MjExMTI1", "url": "https://api.github.com/repos/hgrecco/pint/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-01-03T23:01:44Z", "updated_at": "2013-01-04T14:35:13Z", "closed_at": "2013-01-04T14:35:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "``` python\n>>> from pint import UnitRegistry\n>>> ureg = UnitRegistry()\n>>> Q_ = ureg.Quantity\n>>> Q_('0 * degK').to('degC')\n<Quantity(0.0, 'degC')>\n>>> Q_('0 * degC').to('degF')\n<Quantity(0.0, 'degF')>\n>>> Q_('100 * degC').to('degF')\n<Quantity(55.55555555555556, 'degF')>\n>>> Q_('212 * degF').to('degC')\n<Quantity(381.6, 'degC')>\n```\n\nIt seems like the \"offset\" parameter in the definition file is being ignored.  The test_offset method in test_pint.py is decorated with unittest.expectedFailure.\n", "reactions": {"url": "https://api.github.com/repos/hgrecco/pint/issues/3/reactions", "total_count": 0, "+1": 0, "-1": 0, "laugh": 0, "hooray": 0, "confused": 0, "heart": 0, "rocket": 0, "eyes": 0}, "timeline_url": "https://api.github.com/repos/hgrecco/pint/issues/3/timeline", "performed_via_github_app": null, "state_reason": "completed"}]